import { useEffect,useMemo,useState } from 'react'
import { CalendarDays,Check,CheckCircle2,Clock3,Coffee,DoorOpen,PhoneCall,RotateCcw,Search,ShoppingBag,UserRoundCheck,X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { useAuth } from '../context/AuthContext'
import { exportPdf,exportXlsx } from '../lib/export'
import { ClientTypeFilter } from '../components/ClientTypeFilter'
import type { ClientTypeFilterValue } from '../components/ClientTypeFilter'
import { CrmTerritoryFilters,type CrmTerritoryMode } from '../components/CrmTerritoryFilters'
import { EMPTY_OFFICIAL_SELECTION,loadOfficialAreaDirectory,matchesOfficialSelection } from '../lib/officialTerritory'
import type { OfficialArea,OfficialSelection } from '../lib/officialTerritory'
import { loadGeoAssessmentMap } from '../lib/geoQuality'
import type { GeoAssessment } from '../lib/geoQuality'
import { loadClientsPaged } from '../lib/clientLoader'

const CLIENT_COLUMNS='id,codempr,client_type,legal_name,vendor_employee_id,manager_employee_id,region,province,municipality'
const todayKey=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Santo_Domingo'})
const sourceLabel=(value?:string)=>value==='VISITA'?'Visita vendedor':value==='LLAMADA'?'Llamada CRM':value==='RECEPCION'?'Recepción':value||'Manual'
const money=(value:any)=>`RD$${Number(value||0).toLocaleString('es-DO',{maximumFractionDigits:2})}`

export function AgendaV2(){
 const {employee}=useAuth();const admin=['Administrador','Supervisor'].includes(employee?.app_role||'')
 const [rows,setRows]=useState<any[]>([]),[receptions,setReceptions]=useState<any[]>([]),[sessions,setSessions]=useState<any[]>([]),[employees,setEmployees]=useState<any[]>([]),[clients,setClients]=useState<any[]>([])
 const [officialAreas,setOfficialAreas]=useState<OfficialArea[]>([]),[geoAssessments,setGeoAssessments]=useState<Map<string,GeoAssessment>>(new Map()),[availability,setAvailability]=useState<any[]>([])
 const [statusFilter,setStatusFilter]=useState(''),[managerFilter,setManagerFilter]=useState(''),[sourceFilter,setSourceFilter]=useState(''),[clientType,setClientType]=useState<ClientTypeFilterValue>(''),[q,setQ]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('')
 const [territoryMode,setTerritoryMode]=useState<CrmTerritoryMode>('MASTER'),[region,setRegion]=useState(''),[province,setProvince]=useState(''),[municipality,setMunicipality]=useState(''),[officialSelection,setOfficialSelection]=useState<OfficialSelection>(EMPTY_OFFICIAL_SELECTION)
 const [loadError,setLoadError]=useState(''),[validate,setValidate]=useState<any|null>(null),[finish,setFinish]=useState<any|null>(null),[busy,setBusy]=useState(false)

 const load=async()=>{
  setLoadError('')
  const [a,r,s,e,portfolio,areas,assessmentMap,av]=await Promise.all([
   supabase.from('appointments').select('*,clients(id,codempr,legal_name,client_type,phone1,mobile,vendor_employee_id,manager_employee_id,region,province,municipality),prospects(prospect_code,legal_name,phone,mobile),manager:employees!appointments_assigned_manager_id_fkey(id,full_name,employee_type),requester:employees!appointments_requested_by_employee_id_fkey(id,full_name,employee_type)').order('created_at',{ascending:false}).limit(2000),
   supabase.from('reception_entries').select('*,clients(id,codempr,legal_name,client_type,region,province,municipality),prospects(prospect_code,legal_name),manager:employees!reception_entries_assigned_manager_id_fkey(id,full_name)').order('check_in_at',{ascending:false}).limit(1500),
   supabase.from('showroom_sessions').select('*,clients(client_type)').order('started_at',{ascending:false}).limit(1500),
   supabase.from('employees').select('id,full_name,employee_type,app_role,active').eq('active',true).order('full_name'),
   loadClientsPaged(CLIENT_COLUMNS),loadOfficialAreaDirectory(),loadGeoAssessmentMap(),supabase.from('manager_reception_availability_v1').select('*').order('full_name'),
  ])
  const error=a.error||r.error||s.error||e.error||av.error;if(error)setLoadError(error.message)
  setRows(a.data||[]);setReceptions(r.data||[]);setSessions(s.data||[]);setEmployees(e.data||[]);setClients(portfolio);setOfficialAreas(areas);setGeoAssessments(assessmentMap);setAvailability(av.data||[])
 }
 useEffect(()=>{void load()},[])
 useEffect(()=>{setProvince('');setMunicipality('')},[region]);useEffect(()=>setMunicipality(''),[province])
 useEffect(()=>{if(territoryMode==='MASTER')setOfficialSelection(EMPTY_OFFICIAL_SELECTION);else{setRegion('');setProvince('');setMunicipality('')}},[territoryMode])

 const managers=useMemo(()=>employees.filter(e=>e.employee_type==='Gestor'),[employees])
 const territorialClients=useMemo(()=>clients.filter(c=>{
  if(clientType&&c.client_type!==clientType)return false
  if(territoryMode==='MASTER'){if(region&&c.region!==region)return false;if(province&&c.province!==province)return false;if(municipality&&c.municipality!==municipality)return false}
  else if(!matchesOfficialSelection(geoAssessments.get(c.id),officialAreas,officialSelection))return false
  return true
 }),[clients,clientType,territoryMode,region,province,municipality,officialSelection,officialAreas,geoAssessments])
 const territorialIds=useMemo(()=>new Set(territorialClients.map(c=>c.id)),[territorialClients])
 const scopeRows=useMemo(()=>rows.filter(r=>{
  if(r.client_id&&!territorialIds.has(r.client_id))return false;if(clientType&&r.clients?.client_type!==clientType)return false;if(managerFilter&&r.assigned_manager_id!==managerFilter)return false;if(sourceFilter&&r.source_type!==sourceFilter)return false
  const d=r.appointment_at||r.requested_appointment_at||r.requested_at||r.created_at;if(from&&d&&new Date(d)<new Date(`${from}T00:00:00`))return false;if(to&&d&&new Date(d)>new Date(`${to}T23:59:59`))return false
  if(q.trim()){const n=q.trim().toLowerCase();const h=`${r.clients?.legal_name||''} ${r.clients?.codempr||''} ${r.requester?.full_name||''} ${r.manager?.full_name||''} ${r.request_contact_name||''} ${r.request_phone||''} ${r.notes||''}`.toLowerCase();if(!h.includes(n))return false}
  return true
 }),[rows,territorialIds,clientType,managerFilter,sourceFilter,from,to,q])
 const visible=useMemo(()=>scopeRows.filter(r=>!statusFilter||r.status===statusFilter),[scopeRows,statusFilter])
 const receptionByAppointment=useMemo(()=>new Map(receptions.filter(r=>r.appointment_id).map(r=>[r.appointment_id,r])),[receptions]),sessionByReception=useMemo(()=>new Map(sessions.map(s=>[s.reception_entry_id,s])),[sessions])
 const waiting=useMemo(()=>receptions.filter(r=>r.status==='EN_ESPERA'&&(!r.client_id||territorialIds.has(r.client_id))&&(admin||r.assigned_manager_id===employee?.id)),[receptions,territorialIds,admin,employee?.id])
 const activeService=useMemo(()=>receptions.filter(r=>r.status==='EN_ATENCION'&&(admin||r.assigned_manager_id===employee?.id)),[receptions,admin,employee?.id])
 const canManage=(r:any)=>admin||r.assigned_manager_id===employee?.id
 const count=(status:string)=>scopeRows.filter(r=>r.status===status).length
 const today=todayKey(),todayAppointments=scopeRows.filter(r=>r.appointment_at&&new Date(r.appointment_at).toLocaleDateString('en-CA',{timeZone:'America/Santo_Domingo'})===today&&['CONFIRMADA','REPROGRAMADA','PROGRAMADA','ASISTIO','FINALIZADA'].includes(r.status)).length
 const arrived=receptions.filter(r=>new Date(r.check_in_at).toLocaleDateString('en-CA',{timeZone:'America/Santo_Domingo'})===today).length,purchased=sessions.filter(s=>s.purchased===true&&s.ended_at&&new Date(s.ended_at).toLocaleDateString('en-CA',{timeZone:'America/Santo_Domingo'})===today).length
 const ownAvailability=availability.find(a=>a.employee_id===employee?.id)

 const markLunch=async(start:boolean)=>{
  if(!employee?.id)return;setBusy(true)
  try{const workDate=todayKey();if(start){const {error}=await supabase.from('manager_daily_availability').upsert({employee_id:employee.id,work_date:workDate,lunch_started_at:new Date().toISOString(),lunch_ended_at:null,updated_at:new Date().toISOString()},{onConflict:'employee_id,work_date'});if(error)throw error}else{const {error}=await supabase.from('manager_daily_availability').update({lunch_ended_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('employee_id',employee.id).eq('work_date',workDate);if(error)throw error}await load()}catch(e){alert(e instanceof Error?e.message:'No se pudo actualizar disponibilidad')}finally{setBusy(false)}
 }
 const startService=async(entry:any)=>{
  if(!employee?.id)return;if(!entry.assigned_manager_id)return alert('Esta atención no tiene Gestor asignado.');if(!admin&&entry.assigned_manager_id!==employee.id)return alert('Solo el gestor asignado puede iniciar esta atención.');if(ownAvailability?.availability_status==='ALMUERZO'&&!admin)return alert('Marca Regresé del almuerzo antes de iniciar una atención.')
  const existing=sessionByReception.get(entry.id);if(!existing){const responsible=entry.assigned_manager_id;const {error}=await supabase.from('showroom_sessions').insert({reception_entry_id:entry.id,appointment_id:entry.appointment_id||null,client_id:entry.client_id||null,prospect_id:entry.prospect_id||null,manager_employee_id:responsible,attended_by_employee_id:responsible,started_at:new Date().toISOString()});if(error)return alert(error.message)}
  const {error}=await supabase.from('reception_entries').update({status:'EN_ATENCION',service_started_at:new Date().toISOString(),service_started_by:employee.id}).eq('id',entry.id);if(error)return alert(error.message);await load()
 }
 const report=visible.map(r=>({Fecha:r.appointment_at?new Date(r.appointment_at).toLocaleString('es-DO'):'',Region:r.clients?.region||'',Provincia:r.clients?.province||'',Municipio:r.clients?.municipality||'',TipoCliente:r.clients?.client_type||'',Cliente:r.clients?.legal_name||r.prospects?.legal_name||'',Gestor:r.manager?.full_name||'',SolicitadoPor:r.requester?.full_name||'',Origen:sourceLabel(r.source_type),Estado:r.status,Contacto:r.request_contact_name||'',Notas:r.validation_notes||r.notes||''}))

 return <div className="page-stack">
  <div className="page-head"><div><span className="eyebrow">AGENDA Y SHOWROOM</span><h2>Citas, recepción y conversión</h2><p>Interés → validación del Gestor → cita real → llegada → atención → resultado comercial → salida.</p></div><div className="button-row"><button className="secondary" onClick={()=>void exportXlsx('Agenda_Showroom_Territorial',report)}>Excel</button><button className="secondary" onClick={()=>exportPdf('Agenda Showroom',report)}>PDF</button></div></div>
  {employee?.employee_type==='Gestor'&&<div className="panel"><div className="panel-head"><div><b>Mi disponibilidad para Recepción</b><span>Recepción usa este estado para asignar clientes sin Gestor y ver carga actual.</span></div><div className="button-row">{ownAvailability?.availability_status==='ALMUERZO'?<button className="primary" disabled={busy} onClick={()=>void markLunch(false)}><Check/> Regresé del almuerzo</button>:<button className="secondary" disabled={busy||activeService.length>0} onClick={()=>void markLunch(true)}><Coffee/> Salir a comer</button>}</div></div><div className="meta"><span>Estado: <b>{ownAvailability?.availability_status||'DISPONIBLE'}</b></span><span>{ownAvailability?.waiting_clients||0} esperando</span><span>{ownAvailability?.active_clients||0} en atención</span>{ownAvailability?.lunch_started_at&&<span>Almuerzo: {new Date(ownAvailability.lunch_started_at).toLocaleTimeString('es-DO',{hour:'2-digit',minute:'2-digit'})}{ownAvailability.lunch_ended_at?` → ${new Date(ownAvailability.lunch_ended_at).toLocaleTimeString('es-DO',{hour:'2-digit',minute:'2-digit'})}`:''}</span>}</div></div>}
  <div className="kpi-grid"><Kpi label="Por validar" value={count('PENDIENTE_VALIDACION')} sub="requieren llamada del gestor" Icon={PhoneCall}/><Kpi label="Confirmadas" value={count('CONFIRMADA')} sub="citas pactadas" Icon={CheckCircle2}/><Kpi label="Citas hoy" value={todayAppointments} sub="agenda del día" Icon={CalendarDays}/><Kpi label="Esperando" value={waiting.length} sub="ya llegaron" Icon={DoorOpen}/><Kpi label="En atención" value={activeService.length} sub="gestiones abiertas" Icon={UserRoundCheck}/><Kpi label="Compraron hoy" value={purchased} sub="showroom" Icon={ShoppingBag}/></div>
  <div className="panel planner-filter-panel"><CrmTerritoryFilters clients={clients} mode={territoryMode} onModeChange={setTerritoryMode} region={region} onRegionChange={setRegion} province={province} onProvinceChange={setProvince} municipality={municipality} onMunicipalityChange={setMunicipality} officialAreas={officialAreas} officialSelection={officialSelection} onOfficialSelectionChange={setOfficialSelection}/><div className="planner-filter-grid"><div className="search-field"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cliente, código, contacto, responsable..."/></div><ClientTypeFilter value={clientType} onChange={setClientType}/><select value={managerFilter} onChange={e=>setManagerFilter(e.target.value)}><option value="">Todos los gestores</option>{managers.map(m=><option value={m.id} key={m.id}>{m.full_name}</option>)}</select><select value={sourceFilter} onChange={e=>setSourceFilter(e.target.value)}><option value="">Todos los orígenes</option><option value="LLAMADA">Llamada CRM</option><option value="VISITA">Visita vendedor</option><option value="MANUAL">Manual</option></select><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">Todos los estados</option><option value="PENDIENTE_VALIDACION">Pendiente validación</option><option value="CONTACTANDO">Contactando</option><option value="CONFIRMADA">Confirmada</option><option value="REPROGRAMADA">Reprogramada</option><option value="NO_CONFIRMADA">No confirmada</option><option value="CANCELADA">Cancelada</option><option value="ASISTIO">Asistió</option><option value="NO_ASISTIO">No asistió</option><option value="FINALIZADA">Finalizada</option></select><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></div><div className="planner-filter-actions"><div className="meta"><span>{visible.length} gestiones</span><span>{waiting.length} esperando</span></div><button className="secondary" onClick={()=>{setQ('');setClientType('');setTerritoryMode('MASTER');setRegion('');setProvince('');setMunicipality('');setOfficialSelection(EMPTY_OFFICIAL_SELECTION);setManagerFilter('');setSourceFilter('');setStatusFilter('');setFrom('');setTo('')}}>Limpiar filtros</button></div></div>
  {loadError&&<div className="panel"><b>Error cargando Agenda / Showroom</b><span>{loadError}</span></div>}
  {(waiting.length>0||activeService.length>0)&&<div className="panel"><div className="panel-head"><div><b>Clientes en Recepción</b><span>La presencia física viene de Recepción; el Gestor controla la atención comercial.</span></div><span className="badge">{waiting.length+activeService.length}</span></div><div className="cards-list">{waiting.map(entry=><div className="activity-card" key={entry.id}><div className="activity-main"><b>{entry.clients?.legal_name||entry.prospects?.legal_name||entry.company_name||entry.visitor_name}</b><span>Esperando desde {new Date(entry.check_in_at).toLocaleTimeString('es-DO',{hour:'2-digit',minute:'2-digit'})} · {entry.manager?.full_name||'Sin gestor'}</span><small>{entry.purpose||'Atención comercial'}</small></div><button className="primary compact" onClick={()=>void startService(entry)}><UserRoundCheck size={15}/> Iniciar atención</button></div>)}{activeService.map(entry=>{const session=sessionByReception.get(entry.id);return <div className="activity-card open" key={entry.id}><div className="activity-main"><b>{entry.clients?.legal_name||entry.prospects?.legal_name||entry.company_name||entry.visitor_name}</b><span>En atención · inició {entry.service_started_at?new Date(entry.service_started_at).toLocaleTimeString('es-DO',{hour:'2-digit',minute:'2-digit'}):'—'}</span><small>Recepción registrará la salida física después del cierre comercial.</small></div>{session&&<button className="primary compact" onClick={()=>setFinish({entry,session})}><ShoppingBag size={15}/> Finalizar atención</button>}</div>})}</div></div>}
  <div className="panel"><div className="panel-head"><div><b>Embudo de citas</b><span>Una solicitud no cuenta como cita pactada hasta que el Gestor confirma fecha y hora real.</span></div><span className="badge">{visible.length}</span></div><div className="calendar-list">{visible.length===0&&<div className="empty-state"><b>No hay citas con los filtros actuales.</b></div>}{visible.map(r=>{const reception=receptionByAppointment.get(r.id),displayDate=r.appointment_at||r.requested_appointment_at;return <div className="appointment-card" key={r.id}><div className="date-box">{displayDate?<><b>{new Date(displayDate).getDate()}</b><span>{new Date(displayDate).toLocaleDateString('es-DO',{month:'short'})}</span></>:<><Clock3/><span>Por definir</span></>}</div><div className="activity-main"><b>{r.clients?.legal_name||r.prospects?.legal_name||'Cita'}</b><span>{displayDate?new Date(displayDate).toLocaleString('es-DO'):'Sin fecha tentativa'} · Gestor: {r.manager?.full_name||'Sin responsable'}</span><small>{r.status.replaceAll('_',' ')} · <b>{sourceLabel(r.source_type)}</b>{r.requester?.full_name?` · solicitado por ${r.requester.full_name}`:''}</small>{r.request_contact_name&&<small>Contacto: {r.request_contact_name}{r.request_phone?` · ${r.request_phone}`:''}</small>}{r.validation_notes&&<small>Validación: {r.validation_notes}</small>}{reception&&<small>Llegada: {new Date(reception.check_in_at).toLocaleString('es-DO')} · {reception.status.replaceAll('_',' ')}</small>}</div>{canManage(r)&&['PENDIENTE_VALIDACION','CONTACTANDO'].includes(r.status)&&r.assigned_manager_id&&<div className="row-actions"><button className="primary compact" onClick={()=>setValidate(r)}><PhoneCall size={15}/> Validar</button></div>}</div>})}</div></div>
  {validate&&<ValidateAppointment row={validate} employeeId={employee?.id||''} onClose={()=>setValidate(null)} onSaved={async()=>{setValidate(null);await load()}}/>}
  {finish&&<FinishShowroom data={finish} employeeId={employee?.id||''} onClose={()=>setFinish(null)} onSaved={async()=>{setFinish(null);await load()}}/>}
 </div>
}

function Kpi({label,value,sub,Icon}:{label:string;value:any;sub:string;Icon:any}){return <div className="kpi-card"><div className="kpi-icon"><Icon/></div><div><span>{label}</span><strong>{value}</strong><small>{sub}</small></div></div>}

function ValidateAppointment({row,employeeId,onClose,onSaved}:{row:any;employeeId:string;onClose:()=>void;onSaved:()=>Promise<void>|void}){
 const initial=row.appointment_at||row.requested_appointment_at;const local=initial?new Date(new Date(initial).getTime()-new Date(initial).getTimezoneOffset()*60000).toISOString().slice(0,16):''
 const [dateTime,setDateTime]=useState(local),[confirmed,setConfirmed]=useState(false),[notes,setNotes]=useState(row.validation_notes||''),[busy,setBusy]=useState(false)
 const save=async(status:'CONFIRMADA'|'REPROGRAMADA'|'NO_CONFIRMADA'|'CANCELADA')=>{if(['CONFIRMADA','REPROGRAMADA'].includes(status)&&(!dateTime||!confirmed))return alert('Selecciona y confirma la fecha/hora real pactada con el cliente.');setBusy(true);try{const patch:any={status,validation_notes:notes||null};if(['CONFIRMADA','REPROGRAMADA'].includes(status)){patch.appointment_at=new Date(dateTime).toISOString();patch.confirmed_at=new Date().toISOString();patch.confirmed_by_employee_id=employeeId}else{patch.confirmed_at=null;patch.confirmed_by_employee_id=null}const {error}=await supabase.from('appointments').update(patch).eq('id',row.id);if(error)throw error;await onSaved()}catch(e){alert(e instanceof Error?e.message:'No se pudo validar la cita')}finally{setBusy(false)}}
 return <div className="modal-wrap"><button className="modal-backdrop" onClick={onClose}/><div className="modal"><div className="modal-head"><div><span className="eyebrow">VALIDACIÓN SHOWROOM</span><h3>{row.clients?.legal_name||row.prospects?.legal_name||'Cliente'}</h3><p>Contacta al cliente y registra la fecha/hora real acordada.</p></div><button className="icon-btn" onClick={onClose}><X/></button></div><div className="form-grid"><label className="span-2">Fecha/hora pactada<div style={{display:'flex',gap:8,alignItems:'center'}}><input type="datetime-local" value={dateTime} onChange={e=>{setDateTime(e.target.value);setConfirmed(false)}}/><button type="button" className="secondary compact" disabled={!dateTime} onClick={()=>{setConfirmed(true);(document.activeElement as HTMLElement|null)?.blur()}}><Check size={15}/> Confirmar</button></div><small>{confirmed&&dateTime?`✓ Confirmada: ${new Date(dateTime).toLocaleString('es-DO')}`:'Selecciona fecha/hora y pulsa Confirmar.'}</small></label><label className="span-2">Nota de validación<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Cliente confirma, solicita cambio, condiciones de la visita..."/></label></div><div className="modal-actions"><button className="secondary" disabled={busy} onClick={()=>void save('NO_CONFIRMADA')}>No confirmó</button><button className="secondary" disabled={busy} onClick={()=>void save('CANCELADA')}>Cancelar solicitud</button><button className="secondary" disabled={busy} onClick={()=>void save('REPROGRAMADA')}><RotateCcw size={15}/> Reprogramar</button><button className="primary" disabled={busy} onClick={()=>void save('CONFIRMADA')}><CheckCircle2 size={15}/> Confirmar cita</button></div></div></div>
}

function FinishShowroom({data,employeeId,onClose,onSaved}:{data:any;employeeId:string;onClose:()=>void;onSaved:()=>Promise<void>|void}){
 const {entry,session}=data;const [outcome,setOutcome]=useState('SEGUIMIENTO'),[amount,setAmount]=useState(''),[attendedBy,setAttendedBy]=useState(''),[nextAction,setNextAction]=useState(''),[followUp,setFollowUp]=useState(''),[notes,setNotes]=useState(''),[busy,setBusy]=useState(false)
 const purchased=outcome==='COMPRA'
 const save=async()=>{if(purchased&&Number(amount)<=0)return alert('Indica el monto de la compra.');setBusy(true);try{const endedAt=new Date().toISOString();const {error}=await supabase.from('showroom_sessions').update({ended_at:endedAt,outcome,purchased,purchase_amount:purchased?Number(amount):null,attended_by_name:attendedBy||null,attended_by_employee_id:employeeId,next_action:nextAction||null,follow_up_date:followUp||null,notes:notes||null}).eq('id',session.id);if(error)throw error;const {error:rError}=await supabase.from('reception_entries').update({status:'ATENCION_FINALIZADA',service_ended_at:endedAt,service_ended_by:employeeId}).eq('id',entry.id);if(rError)throw rError;if(entry.appointment_id){const {error:aError}=await supabase.from('appointments').update({status:'FINALIZADA',purchased}).eq('id',entry.appointment_id);if(aError)throw aError}await onSaved()}catch(e){alert(e instanceof Error?e.message:'No se pudo finalizar la atención')}finally{setBusy(false)}}
 return <div className="modal-wrap"><button className="modal-backdrop" onClick={onClose}/><div className="modal"><div className="modal-head"><div><span className="eyebrow">CIERRE SHOWROOM</span><h3>{entry.clients?.legal_name||entry.company_name||entry.visitor_name}</h3><p>Finaliza la gestión comercial; Recepción registrará posteriormente la salida física.</p></div><button className="icon-btn" onClick={onClose}><X/></button></div><div className="form-grid"><label>Resultado<select value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="COMPRA">Compró</option><option value="NO_COMPRA">No compró</option><option value="PENDIENTE">Pendiente</option><option value="SEGUIMIENTO">Seguimiento</option><option value="COTIZACION">Cotización</option><option value="OTRO">Otro</option></select></label><label>Quién atendió<input value={attendedBy} onChange={e=>setAttendedBy(e.target.value)} placeholder="Nombre de quien atendió"/></label>{purchased&&<label className="span-2">Monto compra RD$<input type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/><small>Se sumará al resultado ejecutivo del showroom.</small></label>}<label>Próxima acción<input value={nextAction} onChange={e=>setNextAction(e.target.value)} placeholder="Seguimiento, cotización, llamada..."/></label><label>Fecha seguimiento<input type="date" value={followUp} onChange={e=>setFollowUp(e.target.value)}/></label><label className="span-2">Observación<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><div className="modal-actions"><button className="secondary" onClick={onClose}>Cancelar</button><button className="primary" disabled={busy} onClick={()=>void save()}>{busy?'Guardando...':purchased?`Finalizar · ${money(amount)}`:'Finalizar atención'}</button></div></div></div>
}
