import { useEffect,useMemo,useState } from 'react'
import { CalendarDays,Check,CheckCircle2,Clock3,Coffee,DoorOpen,PhoneCall,RotateCcw,Search,ShoppingBag,UserRoundCheck,X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { useAuth } from '../context/AuthContext'
import { exportPdf,exportXlsx } from '../lib/export'
import { ClientTypeFilter } from '../components/ClientTypeFilter'
import type { ClientTypeFilterValue } from '../components/ClientTypeFilter'
import { CrmTerritoryFilters,type CrmTerritoryMode } from '../components/CrmTerritoryFilters'
import { EMPTY_OFFICIAL_SELECTION,loadOfficialAreaDirectory,matchesOfficialSelection } from '../lib/officialTerritory'
import type { OfficialArea,OfficialSelection } from '../lib/officialTerritory'
import { loadGeoAssessmentMap } from '../lib/geoQuality'
import type { GeoAssessment } from '../lib/geoQuality'
import { loadClientsPaged } from '../lib/clientLoader'

const CLIENT_COLUMNS='id,codempr,client_type,legal_name,vendor_employee_id,manager_employee_id,region,province,municipality'
const todayKey=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Santo_Domingo'})
const sourceLabel=(value?:string)=>value==='VISITA'?'Visita vendedor':value==='LLAMADA'?'Llamada CRM':value==='RECEPCION'?'Recepción':value||'Manual'
const money=(value:any)=>`RD$${Number(value||0).toLocaleString('es-DO',{maximumFractionDigits:2})}`
const SHOWROOM_NEXT_ACTIONS=[['','Sin próxima acción'],['LLAMAR','Llamar / volver a llamar'],['VOLVER_VISITAR','Volver a visitar'],['ENVIAR_INFO','Enviar información'],['COTIZACION','Cotización / enviar cotización'],['SHOWROOM','Visita / seguimiento showroom'],['SEGUIMIENTO_PEDIDO','Seguimiento de pedido'],['OTRO','Otro seguimiento']] as const
const SHOWROOM_OUTCOMES=[['COMPRA','Compró'],['NO_COMPRA','No compró'],['PENDIENTE','Pendiente'],['SEGUIMIENTO','Seguimiento'],['COTIZACION','Cotización'],['OTRO','Otro']] as const
const showroomOutcomeLabel=(value?:string|null)=>SHOWROOM_OUTCOMES.find(([key])=>key===value)?.[1]||value||'Sin resultado'

export function AgendaV2(){
 const {employee}=useAuth();const admin=['Administrador','Supervisor'].includes(employee?.app_role||''),isAmountAdmin=employee?.app_role==='Administrador',managerViewer=employee?.employee_type==='Gestor'
 const [rows,setRows]=useState<any[]>([]),[receptions,setReceptions]=useState<any[]>([]),[sessions,setSessions]=useState<any[]>([]),[employees,setEmployees]=useState<any[]>([]),[clients,setClients]=useState<any[]>([])
 const [officialAreas,setOfficialAreas]=useState<OfficialArea[]>([]),[geoAssessments,setGeoAssessments]=useState<Map<string,GeoAssessment>>(new Map()),[availability,setAvailability]=useState<any[]>([])
 const [statusFilter,setStatusFilter]=useState(''),[managerFilter,setManagerFilter]=useState(''),[sourceFilter,setSourceFilter]=useState(''),[clientType,setClientType]=useState<ClientTypeFilterValue>(''),[q,setQ]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('')
 const [territoryMode,setTerritoryMode]=useState<CrmTerritoryMode>('MASTER'),[region,setRegion]=useState(''),[province,setProvince]=useState(''),[municipality,setMunicipality]=useState(''),[officialSelection,setOfficialSelection]=useState<OfficialSelection>(EMPTY_OFFICIAL_SELECTION)
 const [loadError,setLoadError]=useState(''),[validate,setValidate]=useState<any|null>(null),[finish,setFinish]=useState<any|null>(null),[amountEdit,setAmountEdit]=useState<any|null>(null),[busy,setBusy]=useState(false)

 const load=async()=>{
  setLoadError('')
  const [a,r,s,e,portfolio,areas,assessmentMap,av]=await Promise.all([
   supabase.from('appointments').select('*,clients(id,codempr,legal_name,client_type,phone1,mobile,vendor_employee_id,manager_employee_id,region,province,municipality),prospects(prospect_code,legal_name,phone,mobile),manager:employees!appointments_assigned_manager_id_fkey(id,full_name,employee_type),requester:employees!appointments_requested_by_employee_id_fkey(id,full_name,employee_type)').order('created_at',{ascending:false}).limit(2000),
   supabase.from('reception_entries').select('*,clients(id,codempr,legal_name,client_type,region,province,municipality),prospects(prospect_code,legal_name),manager:employees!reception_entries_assigned_manager_id_fkey(id,full_name)').order('check_in_at',{ascending:false}).limit(1500),
   supabase.from('showroom_sessions').select('*,clients(client_type)').order('started_at',{ascending:false}).limit(1500),
   supabase.from('employees').select('id,full_name,employee_type,app_role,active').eq('active',true).order('full_name'),
   loadClientsPaged(CLIENT_COLUMNS),loadOfficialAreaDirectory(),loadGeoAssessmentMap(),supabase.from('manager_reception_availability_v1').select('*').order('full_name'),
  ])
  const error=a.error||r.error||s.error||e.error||av.error;if(error)setLoadError(error.message)
  setRows(a.data||[]);setReceptions(r.data||[]);setSessions(s.data||[]);setEmployees(e.data||[]);setClients(portfolio);setOfficialAreas(areas);setGeoAssessments(assessmentMap);setAvailability(av.data||[])
 }
 useEffect(()=>{void load()},[])
 useEffect(()=>{setProvince('');setMunicipality('')},[region]);useEffect(()=>setMunicipality(''),[province])
 useEffect(()=>{if(territoryMode==='MASTER')setOfficialSelection(EMPTY_OFFICIAL_SELECTION);else{setRegion('');setProvince('');setMunicipality('')}},[territoryMode])

 const managers=useMemo(()=>employees.filter(e=>e.employee_type==='Gestor'),[employees])
 const territorialClients=useMemo(()=>clients.filter(c=>{
  if(clientType&&c.client_type!==clientType)return false
  if(territoryMode==='MASTER'){if(region&&c.region!==region)return false;if(province&&c.province!==province)return false;if(municipality&&c.municipality!==municipality)return false}
  else if(!matchesOfficialSelection(geoAssessments.get(c.id),officialAreas,officialSelection))return false
  return true
 }),[clients,clientType,territoryMode,region,province,municipality,officialSelection,officialAreas,geoAssessments])
 const territorialIds=useMemo(()=>new Set(territorialClients.map(c=>c.id)),[territorialClients])
 const scopeRows=useMemo(()=>rows.filter(r=>{
  if(r.client_id&&!territorialIds.has(r.client_id))return false;if(clientType&&r.clients?.client_type!==clientType)return false;if(managerFilter&&r.assigned_manager_id!==managerFilter)return false;if(sourceFilter&&r.source_type!==sourceFilter)return false
  const d=r.appointment_at||r.requested_appointment_at||r.requested_at||r.created_at;if(from&&d&&new Date(d)<new Date(`${from}T00:00:00`))return false;if(to&&d&&new Date(d)>new Date(`${to}T23:59:59`))return false
  if(q.trim()){const n=q.trim().toLowerCase();const h=`${r.clients?.legal_name||''} ${r.clients?.codempr||''} ${r.requester?.full_name||''} ${r.manager?.full_name||''} ${r.request_contact_name||''} ${r.request_phone||''} ${r.notes||''}`.toLowerCase();if(!h.includes(n))return false}
  return true
 }),[rows,territorialIds,clientType,managerFilter,sourceFilter,from,to,q])
 const visible=useMemo(()=>scopeRows.filter(r=>!statusFilter||r.status===statusFilter),[scopeRows,statusFilter])
 const receptionByAppointment=useMemo(()=>new Map(receptions.filter(r=>r.appointment_id).map(r=>[r.appointment_id,r])),[receptions])
 const sessionByReception=useMemo(()=>new Map(sessions.map(s=>[s.reception_entry_id,s])),[sessions])
 const sessionByAppointment=useMemo(()=>new Map(sessions.filter(s=>s.appointment_id).map(s=>[s.appointment_id,s])),[sessions])
 const canSeeAllReception=admin||managerViewer
 const receptionInScope=useMemo(()=>receptions.filter(r=>(!r.client_id||territorialIds.has(r.client_id))&&(canSeeAllReception||r.assigned_manager_id===employee?.id)),[receptions,territorialIds,canSeeAllReception,employee?.id])
 const waiting=useMemo(()=>receptionInScope.filter(r=>r.status==='EN_ESPERA'),[receptionInScope])
 const activeService=useMemo(()=>receptionInScope.filter(r=>r.status==='EN_ATENCION'),[receptionInScope])
 const receptionMovements=useMemo(()=>receptionInScope.filter(r=>{const sameDay=new Date(r.check_in_at).toLocaleDateString('en-CA',{timeZone:'America/Santo_Domingo'})===todayKey(),session=sessionByReception.get(r.id),pendingAmount=isAmountAdmin&&session?.purchased===true&&session?.purchase_amount==null;return sameDay||['EN_ESPERA','EN_ATENCION'].includes(r.status)||pendingAmount}),[receptionInScope,sessionByReception,isAmountAdmin])
 const canManage=(r:any)=>admin||r.assigned_manager_id===employee?.id
 const count=(status:string)=>scopeRows.filter(r=>r.status===status).length
 const today=todayKey(),todayAppointments=scopeRows.filter(r=>r.appointment_at&&new Date(r.appointment_at).toLocaleDateString('en-CA',{timeZone:'America/Santo_Domingo'})===today&&['CONFIRMADA','REPROGRAMADA','PROGRAMADA','ASISTIO','FINALIZADA'].includes(r.status)).length
 const todayClosedShowroom=sessions.filter(s=>s.ended_at&&new Date(s.ended_at).toLocaleDateString('en-CA',{timeZone:'America/Santo_Domingo'})===today)
 const purchased=todayClosedShowroom.filter(s=>s.purchased===true).length
 const pendingPurchaseAmounts=todayClosedShowroom.filter(s=>s.purchased===true&&s.purchase_amount==null).length
 const showroomSalesToday=todayClosedShowroom.filter(s=>s.purchased===true).reduce((sum,s)=>sum+Number(s.purchase_amount||0),0)
 const ownAvailability=availability.find(a=>a.employee_id===employee?.id)

 const markLunch=async(start:boolean)=>{
  if(!employee?.id)return;setBusy(true)
  try{const workDate=todayKey();if(start){const {error}=await supabase.from('manager_daily_availability').upsert({employee_id:employee.id,work_date:workDate,lunch_started_at:new Date().toISOString(),lunch_ended_at:null,updated_at:new Date().toISOString()},{onConflict:'employee_id,work_date'});if(error)throw error}else{const {error}=await supabase.from('manager_daily_availability').update({lunch_ended_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('employee_id',employee.id).eq('work_date',workDate);if(error)throw error}await load()}catch(e){alert(e instanceof Error?e.message:'No se pudo actualizar disponibilidad')}finally{setBusy(false)}
 }
 const startService=async(entry:any)=>{
  if(!employee?.id)return;if(!entry.assigned_manager_id)return alert('Esta atención no tiene Gestor asignado.');if(!admin&&entry.assigned_manager_id!==employee.id)return alert('Solo el gestor asignado puede iniciar esta atención.');if(ownAvailability?.availability_status==='ALMUERZO'&&!admin)return alert('Marca Regresé del almuerzo antes de iniciar una atención.')
  const existing=sessionByReception.get(entry.id);if(!existing){const responsible=entry.assigned_manager_id;const {error}=await supabase.from('showroom_sessions').insert({reception_entry_id:entry.id,appointment_id:entry.appointment_id||null,client_id:entry.client_id||null,prospect_id:entry.prospect_id||null,manager_employee_id:responsible,attended_by_employee_id:responsible,started_at:new Date().toISOString()});if(error)return alert(error.message)}
  const {error}=await supabase.from('reception_entries').update({status:'EN_ATENCION',service_started_at:new Date().toISOString(),service_started_by:employee.id}).eq('id',entry.id);if(error)return alert(error.message);await load()
 }
 const report=visible.map(r=>{const session=sessionByAppointment.get(r.id);return{Fecha:r.appointment_at?new Date(r.appointment_at).toLocaleString('es-DO'):'',Region:r.clients?.region||'',Provincia:r.clients?.province||'',Municipio:r.clients?.municipality||'',TipoCliente:r.clients?.client_type||'',Cliente:r.clients?.legal_name||r.prospects?.legal_name||'',Gestor:r.manager?.full_name||'',SolicitadoPor:r.requester?.full_name||'',Origen:sourceLabel(r.source_type),Estado:r.status,ResultadoShowroom:session?.outcome?showroomOutcomeLabel(session.outcome):'',MontoVentaShowroom:session?.purchase_amount==null?'':Number(session.purchase_amount),EstadoMonto:session?.purchased?(session.purchase_amount==null?'PENDIENTE':'REGISTRADO'):'',Contacto:r.request_contact_name||'',Notas:session?.notes||r.validation_notes||r.notes||''}})

 return <div className="page-stack">
  <div className="page-head"><div><span className="eyebrow">AGENDA Y SHOWROOM</span><h2>Citas, recepción y conversión</h2><p>Interés → validación del Gestor → cita real → llegada → atención → resultado comercial → salida.</p></div><div className="button-row"><button className="secondary" onClick={()=>void exportXlsx('Agenda_Showroom_Territorial',report)}>Excel</button><button className="secondary" onClick={()=>exportPdf('Agenda Showroom',report)}>PDF</button></div></div>
  {employee?.employee_type==='Gestor'&&<div className="panel"><div className="panel-head"><div><b>Mi disponibilidad para Recepción</b><span>Recepción usa este estado para asignar clientes sin Gestor y ver carga actual.</span></div><div className="button-row">{ownAvailability?.availability_status==='ALMUERZO'?<button className="primary" disabled={busy} onClick={()=>void markLunch(false)}><Check/> Regresé del almuerzo</button>:<button className="secondary" disabled={busy||activeService.some(r=>r.assigned_manager_id===employee?.id)} onClick={()=>void markLunch(true)}><Coffee/> Salir a comer</button>}</div></div><div className="meta"><span>Estado: <b>{ownAvailability?.availability_status||'DISPONIBLE'}</b></span><span>{ownAvailability?.waiting_clients||0} esperando</span><span>{ownAvailability?.active_clients||0} en atención</span>{ownAvailability?.lunch_started_at&&<span>Almuerzo: {new Date(ownAvailability.lunch_started_at).toLocaleTimeString('es-DO',{hour:'2-digit',minute:'2-digit'})}{ownAvailability.lunch_ended_at?` → ${new Date(ownAvailability.lunch_ended_at).toLocaleTimeString('es-DO',{hour:'2-digit',minute:'2-digit'})}`:''}</span>}</div></div>}
  <div className="kpi-grid"><Kpi label="Por validar" value={count('PENDIENTE_VALIDACION')} sub="requieren llamada del gestor" Icon={PhoneCall}/><Kpi label="Confirmadas" value={count('CONFIRMADA')} sub="citas pactadas" Icon={CheckCircle2}/><Kpi label="Citas hoy" value={todayAppointments} sub="agenda del día" Icon={CalendarDays}/><Kpi label="Esperando" value={waiting.length} sub="visibles para todos los gestores" Icon={DoorOpen}/><Kpi label="En atención" value={activeService.length} sub="movimientos visibles" Icon={UserRoundCheck}/><Kpi label="Compraron hoy" value={purchased} sub={`${money(showroomSalesToday)} registrados${pendingPurchaseAmounts?` · ${pendingPurchaseAmounts} monto${pendingPurchaseAmounts===1?'':'s'} pendiente${pendingPurchaseAmounts===1?'':'s'}`:''}`} Icon={ShoppingBag}/></div>
  <div className="panel planner-filter-panel"><CrmTerritoryFilters clients={clients} mode={territoryMode} onModeChange={setTerritoryMode} region={region} onRegionChange={setRegion} province={province} onProvinceChange={setProvince} municipality={municipality} onMunicipalityChange={setMunicipality} officialAreas={officialAreas} officialSelection={officialSelection} onOfficialSelectionChange={setOfficialSelection}/><div className="planner-filter-grid"><div className="search-field"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cliente, código, contacto, responsable..."/></div><ClientTypeFilter value={clientType} onChange={setClientType}/><select value={managerFilter} onChange={e=>setManagerFilter(e.target.value)}><option value="">Todos los gestores</option>{managers.map(m=><option value={m.id} key={m.id}>{m.full_name}</option>)}</select><select value={sourceFilter} onChange={e=>setSourceFilter(e.target.value)}><option value="">Todos los orígenes</option><option value="LLAMADA">Llamada CRM</option><option value="VISITA">Visita vendedor</option><option value="MANUAL">Manual</option><option value="RECEPCION">Recepción</option></select><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">Todos los estados</option><option value="PENDIENTE_VALIDACION">Pendiente validación</option><option value="CONTACTANDO">Contactando</option><option value="CONFIRMADA">Confirmada</option><option value="REPROGRAMADA">Reprogramada</option><option value="NO_CONFIRMADA">No confirmada</option><option value="CANCELADA">Cancelada</option><option value="ASISTIO">Asistió</option><option value="NO_ASISTIO">No asistió</option><option value="FINALIZADA">Finalizada</option></select><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></div><div className="planner-filter-actions"><div className="meta"><span>{visible.length} gestiones</span><span>{waiting.length} esperando</span></div><button className="secondary" onClick={()=>{setQ('');setClientType('');setTerritoryMode('MASTER');setRegion('');setProvince('');setMunicipality('');setOfficialSelection(EMPTY_OFFICIAL_SELECTION);setManagerFilter('');setSourceFilter('');setStatusFilter('');setFrom('');setTo('')}}>Limpiar filtros</button></div></div>
  {loadError&&<div className="panel"><b>Error cargando Agenda / Showroom</b><span>{loadError}</span></div>}
  {receptionMovements.length>0&&<div className="panel"><div className="panel-head"><div><b>Movimientos de Recepción</b><span>Todos los Gestores pueden ver llegadas, espera, atención y cierres; solo el responsable puede ejecutar la atención. Administración completa los montos de compra.</span></div><span className="badge">{receptionMovements.length}</span></div><div className="cards-list">{receptionMovements.map(entry=>{const session=sessionByReception.get(entry.id),manageable=canManage(entry);const closed=session?.ended_at,pendingAmount=session?.purchased===true&&session?.purchase_amount==null;return <div className={`activity-card ${entry.status==='EN_ATENCION'?'open':''}`} key={entry.id}><div className="activity-main"><b>{entry.clients?.legal_name||entry.prospects?.legal_name||entry.company_name||entry.visitor_name}</b><span>Llegó {new Date(entry.check_in_at).toLocaleTimeString('es-DO',{hour:'2-digit',minute:'2-digit'})} · Gestor: {entry.manager?.full_name||'Sin gestor'}</span><small>{entry.purpose||'Atención comercial'} · {String(entry.status).replaceAll('_',' ')}</small>{entry.status==='EN_ATENCION'&&session&&<small><b>Al finalizar se solicitará el resultado comercial de showroom.</b></small>}{closed&&<small><b>Resultado showroom: {showroomOutcomeLabel(session.outcome)}{session.purchased?(session.purchase_amount!=null?` · ${money(session.purchase_amount)}`:' · monto pendiente'):''}</b>{session.attended_by_name?` · atendió ${session.attended_by_name}`:''}</small>}</div><div className="row-actions">{entry.status==='EN_ESPERA'&&manageable&&<button className="primary compact" onClick={()=>void startService(entry)}><UserRoundCheck size={15}/> Iniciar atención</button>}{entry.status==='EN_ATENCION'&&session&&manageable&&<button className="primary compact" onClick={()=>setFinish({entry,session})}><ShoppingBag size={15}/> Registrar resultado / finalizar</button>}{!manageable&&['EN_ESPERA','EN_ATENCION'].includes(entry.status)&&<span className="badge">Asignado a {entry.manager?.full_name||'otro Gestor'}</span>}{closed&&session?.purchased&&isAmountAdmin&&<button className="secondary compact" onClick={()=>setAmountEdit({entry,session})}>{pendingAmount?'Completar monto':'Editar monto'}</button>}{closed&&session?.purchased&&!isAmountAdmin&&pendingAmount&&<span className="badge">Monto pendiente de Administración</span>}{['ATENCION_FINALIZADA','SALIO'].includes(entry.status)&&<span className="badge success">{String(entry.status).replaceAll('_',' ')}</span>}</div></div>})}</div></div>}
  <div className="panel"><div className="panel-head"><div><b>Embudo de citas</b><span>Una solicitud no cuenta como cita pactada hasta que el Gestor confirma fecha y hora real. Todos los Gestores pueden consultar el movimiento completo.</span></div><span className="badge">{visible.length}</span></div><div className="calendar-list">{visible.length===0&&<div className="empty-state"><b>No hay citas con los filtros actuales.</b></div>}{visible.map(r=>{const reception=receptionByAppointment.get(r.id),session=sessionByAppointment.get(r.id),displayDate=r.appointment_at||r.requested_appointment_at;return <div className="appointment-card" key={r.id}><div className="date-box">{displayDate?<><b>{new Date(displayDate).getDate()}</b><span>{new Date(displayDate).toLocaleDateString('es-DO',{month:'short'})}</span></>:<><Clock3/><span>Por definir</span></>}</div><div className="activity-main"><b>{r.clients?.legal_name||r.prospects?.legal_name||'Cita'}</b><span>{displayDate?new Date(displayDate).toLocaleString('es-DO'):'Sin fecha tentativa'} · Gestor: {r.manager?.full_name||'Sin responsable'}</span><small>{r.status.replaceAll('_',' ')} · <b>{sourceLabel(r.source_type)}</b>{r.requester?.full_name?` · solicitado por ${r.requester.full_name}`:''}</small>{r.request_contact_name&&<small>Contacto: {r.request_contact_name}{r.request_phone?` · ${r.request_phone}`:''}</small>}{r.validation_notes&&<small>Validación: {r.validation_notes}</small>}{reception&&<small>Llegada: {new Date(reception.check_in_at).toLocaleString('es-DO')} · {reception.status.replaceAll('_',' ')}</small>}{session?.ended_at&&<small><b>Resultado showroom: {showroomOutcomeLabel(session.outcome)}{session.purchased?(session.purchase_amount!=null?` · ${money(session.purchase_amount)}`:' · monto pendiente'):''}</b></small>}</div>{canManage(r)&&['PENDIENTE_VALIDACION','CONTACTANDO'].includes(r.status)&&r.assigned_manager_id&&<div className="row-actions"><button className="primary compact" onClick={()=>setValidate(r)}><PhoneCall size={15}/> Validar</button></div>}</div>})}</div></div>
  {validate&&<ValidateAppointment row={validate} employeeId={employee?.id||''} onClose={()=>setValidate(null)} onSaved={async()=>{setValidate(null);await load()}}/>}
  {finish&&<FinishShowroom data={finish} employeeId={employee?.id||''} managers={managers} canEditAmount={isAmountAdmin} onClose={()=>setFinish(null)} onSaved={async()=>{setFinish(null);await load()}}/>}
  {amountEdit&&isAmountAdmin&&<EditShowroomAmount data={amountEdit} onClose={()=>setAmountEdit(null)} onSaved={async()=>{setAmountEdit(null);await load()}}/>}
 </div>
}

function Kpi({label,value,sub,Icon}:{label:string;value:any;sub:string;Icon:any}){return <div className="kpi-card"><div className="kpi-icon"><Icon/></div><div><span>{label}</span><strong>{value}</strong><small>{sub}</small></div></div>}

function ValidateAppointment({row,employeeId,onClose,onSaved}:{row:any;employeeId:string;onClose:()=>void;onSaved:()=>Promise<void>|void}){
 const initial=row.appointment_at||row.requested_appointment_at;const local=initial?new Date(new Date(initial).getTime()-new Date(initial).getTimezoneOffset()*60000).toISOString().slice(0,16):''
 const [dateTime,setDateTime]=useState(local),[confirmed,setConfirmed]=useState(false),[notes,setNotes]=useState(row.validation_notes||''),[busy,setBusy]=useState(false)
 const save=async(status:'CONFIRMADA'|'REPROGRAMADA'|'NO_CONFIRMADA'|'CANCELADA')=>{if(['CONFIRMADA','REPROGRAMADA'].includes(status)&&(!dateTime||!confirmed))return alert('Selecciona y confirma la fecha/hora real pactada con el cliente.');setBusy(true);try{const patch:any={status,validation_notes:notes||null};if(['CONFIRMADA','REPROGRAMADA'].includes(status)){patch.appointment_at=new Date(dateTime).toISOString();patch.confirmed_at=new Date().toISOString();patch.confirmed_by_employee_id=employeeId}else{patch.confirmed_at=null;patch.confirmed_by_employee_id=null}const {error}=await supabase.from('appointments').update(patch).eq('id',row.id);if(error)throw error;await onSaved()}catch(e){alert(e instanceof Error?e.message:'No se pudo validar la cita')}finally{setBusy(false)}}
 return <div className="modal-wrap"><button className="modal-backdrop" onClick={onClose}/><div className="modal"><div className="modal-head"><div><span className="eyebrow">VALIDACIÓN SHOWROOM</span><h3>{row.clients?.legal_name||row.prospects?.legal_name||'Cliente'}</h3><p>Contacta al cliente y registra la fecha/hora real acordada.</p></div><button className="icon-btn" onClick={onClose}><X/></button></div><div className="form-grid"><label className="span-2">Fecha/hora pactada<div style={{display:'flex',gap:8,alignItems:'center'}}><input type="datetime-local" value={dateTime} onChange={e=>{setDateTime(e.target.value);setConfirmed(false)}}/><button type="button" className="secondary compact" disabled={!dateTime} onClick={()=>{setConfirmed(true);(document.activeElement as HTMLElement|null)?.blur()}}><Check size={15}/> Confirmar</button></div><small>{confirmed&&dateTime?`✓ Confirmada: ${new Date(dateTime).toLocaleString('es-DO')}`:'Selecciona fecha/hora y pulsa Confirmar.'}</small></label><label className="span-2">Nota de validación<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Cliente confirma, solicita cambio, condiciones de la visita..."/></label></div><div className="modal-actions"><button className="secondary" disabled={busy} onClick={()=>void save('NO_CONFIRMADA')}>No confirmó</button><button className="secondary" disabled={busy} onClick={()=>void save('CANCELADA')}>Cancelar solicitud</button><button className="secondary" disabled={busy} onClick={()=>void save('REPROGRAMADA')}><RotateCcw size={15}/> Reprogramar</button><button className="primary" disabled={busy} onClick={()=>void save('CONFIRMADA')}><CheckCircle2 size={15}/> Confirmar cita</button></div></div></div>
}

function FinishShowroom({data,employeeId,managers,canEditAmount,onClose,onSaved}:{data:any;employeeId:string;managers:any[];canEditAmount:boolean;onClose:()=>void;onSaved:()=>Promise<void>|void}){
 const {entry,session}=data
 const [outcome,setOutcome]=useState(''),[amount,setAmount]=useState(''),[attendedByEmployeeId,setAttendedByEmployeeId]=useState(session.attended_by_employee_id||entry.assigned_manager_id||employeeId),[nextAction,setNextAction]=useState(''),[followUp,setFollowUp]=useState(''),[notes,setNotes]=useState(''),[busy,setBusy]=useState(false)
 const purchased=outcome==='COMPRA',selectedAttendant=managers.find(manager=>manager.id===attendedByEmployeeId)
 const save=async()=>{
  if(!outcome)return alert('Selecciona el resultado comercial de la atención en showroom.')
  if(!attendedByEmployeeId||!selectedAttendant)return alert('Selecciona el Gestor que atendió al cliente.')
  if(canEditAmount&&purchased&&amount.trim()&&Number(amount)<=0)return alert('El monto de venta debe ser mayor que cero o quedar vacío para registrarlo después.')
  setBusy(true)
  try{
   const endedAt=new Date().toISOString(),purchaseAmount=purchased&&canEditAmount&&amount.trim()?Number(amount):null
   const {error}=await supabase.from('showroom_sessions').update({ended_at:endedAt,outcome,purchased,purchase_amount:purchaseAmount,attended_by_name:selectedAttendant.full_name,attended_by_employee_id:attendedByEmployeeId,next_action:nextAction||null,follow_up_date:followUp||null,notes:notes||null}).eq('id',session.id).is('ended_at',null)
   if(error)throw error
   const {error:rError}=await supabase.from('reception_entries').update({status:'ATENCION_FINALIZADA',service_ended_at:endedAt,service_ended_by:employeeId}).eq('id',entry.id).eq('status','EN_ATENCION')
   if(rError)throw rError
   if(entry.appointment_id){const {error:aError}=await supabase.from('appointments').update({status:'FINALIZADA',purchased}).eq('id',entry.appointment_id);if(aError)throw aError}
   await onSaved()
  }catch(e){alert(e instanceof Error?e.message:'No se pudo finalizar la atención')}finally{setBusy(false)}
 }
 const disabled=busy||!outcome||!attendedByEmployeeId
 return <div className="modal-wrap" role="dialog" aria-modal="true" aria-label="Resultado comercial showroom"><button className="modal-backdrop" onClick={onClose}/><div className="modal large"><div className="modal-head"><div><span className="eyebrow">RESULTADO COMERCIAL SHOWROOM</span><h3>{entry.clients?.legal_name||entry.company_name||entry.visitor_name}</h3><p>{entry.appointment_id?'Atención con cita':'Llegada sin cita'} · registra el resultado comercial antes de finalizar. Recepción registrará posteriormente la salida física.</p></div><button className="icon-btn" onClick={onClose}><X/></button></div><div className="form-grid"><label>Resultado comercial *<select value={outcome} onChange={e=>{setOutcome(e.target.value);if(e.target.value!=='COMPRA')setAmount('')}}><option value="">Selecciona resultado...</option>{SHOWROOM_OUTCOMES.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><small>La atención no puede cerrarse sin un resultado explícito.</small></label><label>Quién atendió *<select value={attendedByEmployeeId} onChange={e=>setAttendedByEmployeeId(e.target.value)}><option value="">Selecciona Gestor</option>{managers.map(manager=><option value={manager.id} key={manager.id}>{manager.full_name}</option>)}</select><small>Se registra por separado del Gestor responsable de la cita.</small></label>{purchased&&canEditAmount&&<label className="span-2">Monto de venta RD$ (opcional)<input autoFocus type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Puede quedar vacío"/><small>Solo Administración puede registrar el monto. Si aún no existe la orden, finaliza la atención y complétalo posteriormente.</small></label>}{purchased&&!canEditAmount&&<div className="span-2 panel" style={{padding:12}}><b>Monto de venta: pendiente de Administración</b><small>Puedes finalizar la atención sin monto. Administración lo completará cuando la orden esté digitada.</small></div>}<label>Próxima acción<select value={nextAction} onChange={e=>setNextAction(e.target.value)}>{SHOWROOM_NEXT_ACTIONS.map(([value,label])=><option value={value} key={value||'none'}>{label}</option>)}</select></label><label>Fecha seguimiento<input type="date" value={followUp} onChange={e=>setFollowUp(e.target.value)}/></label><label className="span-2">Observación<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Resultado de la atención, necesidad, cotización, compromiso, pedido o cualquier detalle relevante..."/></label></div><div className="modal-actions"><button className="secondary" disabled={busy} onClick={onClose}>Cancelar</button><button className="primary" disabled={disabled} onClick={()=>void save()}>{busy?'Guardando...':purchased&&canEditAmount&&Number(amount)>0?`Guardar resultado · ${money(amount)}`:'Guardar resultado y finalizar atención'}</button></div></div></div>
}

function EditShowroomAmount({data,onClose,onSaved}:{data:any;onClose:()=>void;onSaved:()=>Promise<void>|void}){
 const {entry,session}=data
 const [amount,setAmount]=useState(session.purchase_amount!=null?String(session.purchase_amount):''),[busy,setBusy]=useState(false)
 const save=async()=>{const value=Number(amount);if(!Number.isFinite(value)||value<=0)return alert('Indica un monto de venta mayor que cero.');setBusy(true);try{const {error}=await supabase.from('showroom_sessions').update({purchase_amount:value,updated_at:new Date().toISOString()}).eq('id',session.id).eq('purchased',true);if(error)throw error;await onSaved()}catch(e){alert(e instanceof Error?e.message:'No se pudo actualizar el monto de showroom')}finally{setBusy(false)}}
 return <div className="modal-wrap" role="dialog" aria-modal="true" aria-label="Monto de compra showroom"><button className="modal-backdrop" onClick={onClose}/><div className="modal"><div className="modal-head"><div><span className="eyebrow">ADMINISTRACIÓN · MONTO SHOWROOM</span><h3>{entry.clients?.legal_name||entry.prospects?.legal_name||entry.company_name||entry.visitor_name}</h3><p>Resultado: Compró. El monto puede completarse cuando la orden esté digitada.</p></div><button className="icon-btn" onClick={onClose}><X/></button></div><div className="form-grid"><label className="span-2">Monto de venta RD$ *<input autoFocus type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.00"/><small>Campo reservado exclusivamente a usuarios con rol Administrador.</small></label></div><div className="modal-actions"><button className="secondary" disabled={busy} onClick={onClose}>Cancelar</button><button className="primary" disabled={busy||Number(amount)<=0} onClick={()=>void save()}>{busy?'Guardando...':'Guardar monto'}</button></div></div></div>
}
