import { useEffect,useMemo,useState } from 'react'
import { CalendarCheck2,CheckCircle2,Clock3,FileSpreadsheet,FilterX,PhoneCall,RefreshCw,ShoppingBag,TimerReset,UsersRound } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { useAuth } from '../context/AuthContext'
import { profileForEmployee } from '../lib/access'
import { exportPdf,exportXlsx } from '../lib/export'
import { MetricCard } from '../components/MetricCard'
import '../styles/product-system.css'
import '../styles/crm-operations.css'

type PeriodMode='TODAY'|'WEEK'|'MONTH'|'RANGE'
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Santo_Domingo'})
const ymd=(d:Date)=>d.toLocaleDateString('en-CA',{timeZone:'America/Santo_Domingo'})
const currentMonth=()=>today().slice(0,7)
const duration=(seconds?:number|null)=>{const total=Math.max(0,Math.round(Number(seconds||0)));const h=Math.floor(total/3600);const m=Math.round((total%3600)/60);return h?`${h} h ${m} min`:`${m} min`}
const money=(value?:number|string|null)=>new Intl.NumberFormat('es-DO',{style:'currency',currency:'DOP',maximumFractionDigits:0}).format(Number(value||0))
const pct=(a:number,b:number)=>b?Math.round((a/b)*1000)/10:0
const sum=(rows:any[],key:string)=>rows.reduce((s,r)=>s+Number(r[key]||0),0)
const time=(v?:string|null)=>v?new Date(v).toLocaleTimeString('es-DO',{hour:'2-digit',minute:'2-digit'}):'—'
function bounds(mode:PeriodMode,month:string,from:string,to:string){const now=today();if(mode==='TODAY')return{from:now,to:now};if(mode==='WEEK'){const base=new Date(`${now}T12:00:00`),day=base.getDay()||7,start=new Date(base);start.setDate(base.getDate()-day+1);return{from:ymd(start),to:now}}if(mode==='MONTH'){const[y,m]=month.split('-').map(Number);return{from:ymd(new Date(y,m-1,1,12)),to:now.slice(0,7)===month?now:ymd(new Date(y,m,0,12))}}return{from:from||now,to:to||from||now}}

export function CrmOperations(){
 const {employee}=useAuth();const profile=profileForEmployee(employee);const executive=['Administrador','Supervisor'].includes(profile)
 const [mode,setMode]=useState<PeriodMode>('MONTH'),[month,setMonth]=useState(currentMonth()),[from,setFrom]=useState(today()),[to,setTo]=useState(today()),[manager,setManager]=useState(''),[rows,setRows]=useState<any[]>([]),[followups,setFollowups]=useState<any[]>([]),[managers,setManagers]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState('')
 const range=useMemo(()=>bounds(mode,month,from,to),[mode,month,from,to])
 const load=async()=>{setLoading(true);setError('');let q=supabase.from('executive_crm_daily_v1').select('*').gte('day',range.from).lte('day',range.to).order('day',{ascending:false});let f=supabase.from('executive_crm_followups_v1').select('*').neq('persisted_status','CANCELADO').order('due_at',{ascending:true});if(manager){q=q.eq('employee_id',manager);f=f.eq('employee_id',manager)}const[daily,fu,staff]=await Promise.all([q,f,executive?supabase.from('employees').select('id,full_name,job_title').eq('active',true).eq('employee_type','Gestor').order('full_name'):Promise.resolve({data:[],error:null}) as any]);const err=daily.error||fu.error||staff.error;if(err)setError(err.message);setRows(daily.data||[]);setFollowups(fu.data||[]);setManagers(staff.data||[]);setLoading(false)}
 useEffect(()=>{void load()},[range.from,range.to,manager,employee?.id])
 const stats=useMemo(()=>{const calls=sum(rows,'calls'),contacted=sum(rows,'calls_contacted'),callSeconds=sum(rows,'call_seconds'),showroom=sum(rows,'showroom_completed'),showroomSeconds=sum(rows,'showroom_seconds'),purchases=sum(rows,'showroom_purchases'),sales=sum(rows,'showroom_sales_amount');return{calls,contacted,contact:pct(contacted,calls),callSeconds,avgCall:calls?callSeconds/calls:0,appointments:sum(rows,'appointments_total'),pendingValidation:sum(rows,'appointments_pending_validation'),confirmed:sum(rows,'appointments_confirmed'),attended:sum(rows,'appointments_attended'),showroom,showroomSeconds,avgShowroom:showroom?showroomSeconds/showroom:0,purchases,sales,conversion:pct(purchases,showroom),followups:followups.filter(f=>!['COMPLETADO','CANCELADO'].includes(f.derived_status)).length,overdue:followups.filter(f=>f.derived_status==='VENCIDO').length,dueToday:followups.filter(f=>f.derived_status==='HOY').length,completed:followups.filter(f=>f.derived_status==='COMPLETADO').length}},[rows,followups])
 const complete=async(id:string)=>{setBusy(id);const{error}=await supabase.rpc('complete_follow_up',{p_follow_up_id:id});setBusy('');if(error)return alert(error.message);await load()}
 const reschedule=async(id:string)=>{const value=window.prompt('Nueva fecha (AAAA-MM-DD):',today());if(!value)return;setBusy(id);const due=`${value}T09:00:00-04:00`;const{error}=await supabase.rpc('reschedule_follow_up',{p_follow_up_id:id,p_due_at:due});setBusy('');if(error)return alert(error.message);await load()}
 const report=rows.map(r=>({Fecha:r.day,Gestor:r.full_name,Llamadas:r.calls,Contactadas:r.calls_contacted,'Contacto %':pct(r.calls_contacted,r.calls),'Tiempo llamadas':duration(r.call_seconds),Citas:r.appointments_total,'Pendientes validación':r.appointments_pending_validation,Confirmadas:r.appointments_confirmed,Atendidas:r.appointments_attended,Showroom:r.showroom_completed,'Tiempo showroom':duration(r.showroom_seconds),Compras:r.showroom_purchases,Ventas:r.showroom_sales_amount,Seguimientos:r.followups_total,'Ventana actividad':duration(r.activity_window_seconds)}))
 return <div className="page-stack crm-operations-page">
  <div className="page-head"><div><span className="eyebrow">CRM / SHOWROOM</span><h2>{executive?'Control de gestión CRM':'Mi gestión CRM'}</h2><p>Llamadas, seguimientos, citas y atención de showroom medidos según la actividad registrada.</p></div><div className="button-row"><button className="secondary" disabled={!rows.length} onClick={()=>void exportXlsx(`CRM_${range.from}_${range.to}`,report)}><FileSpreadsheet size={16}/> Excel</button><button className="secondary" disabled={!rows.length} onClick={()=>exportPdf(`CRM ${range.from} - ${range.to}`,report)}>PDF</button><button className="secondary" onClick={()=>void load()}><RefreshCw size={16}/> Actualizar</button></div></div>
  <section className="panel filter-stack crm-filter-panel"><div className="filter-row"><label>Período<select value={mode} onChange={e=>setMode(e.target.value as PeriodMode)}><option value="TODAY">Hoy</option><option value="WEEK">Semana actual</option><option value="MONTH">Mes</option><option value="RANGE">Rango</option></select></label>{mode==='MONTH'&&<label>Mes<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label>}{mode==='RANGE'&&<><label>Desde<input type="date" value={from} max={today()} onChange={e=>setFrom(e.target.value)}/></label><label>Hasta<input type="date" value={to} max={today()} min={from} onChange={e=>setTo(e.target.value)}/></label></>}{executive&&<label>Gestor<select value={manager} onChange={e=>setManager(e.target.value)}><option value="">Todos los gestores</option>{managers.map(m=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select></label>}</div><div className="journey-filter-foot"><span>{range.from} → {range.to} · {rows.length} registro(s) diarios</span>{manager&&<button className="secondary compact" onClick={()=>setManager('')}><FilterX size={15}/> Limpiar gestor</button>}</div></section>
  {error&&<div className="panel journey-alert danger"><b>No fue posible cargar CRM / Showroom.</b><span>{error}</span></div>}
  {loading?<div className="panel empty-state"><b>Calculando gestión CRM...</b></div>:<>
   <section className="metric-section"><div className="metric-section-head"><div><b>Llamadas y contacto</b><span>Duración real registrada en llamadas.</span></div></div><div className="metric-grid"><MetricCard icon={<PhoneCall/>} label="Llamadas" value={stats.calls} note={`${stats.contacted} contactadas`}/><MetricCard icon={<UsersRound/>} label="Contactabilidad" value={`${stats.contact}%`} note={`${stats.contacted}/${stats.calls} llamadas`} tone="brand"/><MetricCard icon={<Clock3/>} label="Tiempo llamadas" value={duration(stats.callSeconds)} note={`promedio ${duration(stats.avgCall)}`}/><MetricCard icon={<CalendarCheck2/>} label="Citas generadas/registradas" value={stats.appointments} note={`${stats.confirmed} confirmadas`}/></div></section>
   <section className="metric-section"><div className="metric-section-head"><div><b>Showroom y resultado comercial</b><span>Atención efectiva y conversión registrada.</span></div></div><div className="metric-grid"><MetricCard icon={<CalendarCheck2/>} label="Atendidos showroom" value={stats.showroom} note={`${stats.attended} citas marcadas atendidas`}/><MetricCard icon={<TimerReset/>} label="Tiempo showroom" value={duration(stats.showroomSeconds)} note={`promedio ${duration(stats.avgShowroom)}`}/><MetricCard icon={<ShoppingBag/>} label="Clientes con compra" value={stats.purchases} note={`${stats.conversion}% conversión`} tone="success"/><MetricCard icon={<ShoppingBag/>} label="Monto vendido" value={money(stats.sales)} note="ventas showroom registradas" tone="brand" className="metric-money"/></div></section>
   <section className="metric-section"><div className="metric-section-head"><div><b>Cola de seguimiento</b><span>Próximas acciones sincronizadas desde llamadas, visitas y showroom.</span></div></div><div className="metric-grid"><MetricCard icon={<TimerReset/>} label="Pendientes" value={stats.followups} note={`${stats.dueToday} vencen hoy`}/><MetricCard icon={<Clock3/>} label="Vencidos" value={stats.overdue} note="requieren acción" tone={stats.overdue?'danger':'neutral'}/><MetricCard icon={<CheckCircle2/>} label="Completados" value={stats.completed} note="cerrados con trazabilidad" tone="success"/><MetricCard icon={<CalendarCheck2/>} label="Pendientes de validar" value={stats.pendingValidation} note="citas showroom" tone={stats.pendingValidation?'warning':'neutral'}/></div></section>
   <section className="panel crm-worklist"><div className="panel-head"><div><b>Próximas acciones</b><span>Ordenadas por vencimiento. Completar o reprogramar mantiene trazabilidad.</span></div><span>{followups.length}</span></div><div className="crm-followup-list">{followups.filter(f=>f.derived_status!=='CANCELADO').map(f=><div className={`crm-followup-item ${String(f.derived_status).toLowerCase()}`} key={f.id}><div className="crm-followup-status">{f.derived_status}</div><div className="crm-followup-main"><b>{f.subject_name}</b><span>{f.full_name||'Sin asignar'} · {f.source_type} · {new Date(f.due_at).toLocaleDateString('es-DO')}</span><small>{f.notes||'Sin observación'}</small></div><div className="button-row">{f.derived_status!=='COMPLETADO'&&<><button className="secondary compact" disabled={busy===f.id} onClick={()=>void reschedule(f.id)}>Reprogramar</button><button className="primary compact" disabled={busy===f.id} onClick={()=>void complete(f.id)}>{busy===f.id?'Guardando...':'Completar'}</button></>}</div></div>)}{!followups.length&&<div className="empty-state"><CheckCircle2/><b>No hay seguimientos visibles.</b></div>}</div></section>
   <section className="panel crm-daily-table"><div className="panel-head"><div><b>Actividad diaria</b><span>Primera/última actividad son registros operativos, no control de asistencia laboral.</span></div><span>{rows.length}</span></div><div className="journey-table-wrap"><table className="journey-table"><thead><tr><th>Fecha</th>{executive&&<th>Gestor</th>}<th>Llamadas</th><th>Contacto</th><th>Tiempo llam.</th><th>Citas</th><th>Showroom</th><th>Tiempo show.</th><th>Compra</th><th>Actividad</th></tr></thead><tbody>{rows.map(r=><tr key={`${r.employee_id}-${r.day}`}><td><b>{new Date(`${r.day}T12:00:00`).toLocaleDateString('es-DO',{day:'2-digit',month:'short',year:'numeric'})}</b></td>{executive&&<td><b>{r.full_name}</b><small>{r.job_title||'Gestor'}</small></td>}<td>{r.calls}</td><td>{pct(r.calls_contacted,r.calls)}%</td><td>{duration(r.call_seconds)}</td><td>{r.appointments_total}</td><td>{r.showroom_completed}</td><td>{duration(r.showroom_seconds)}</td><td>{r.showroom_purchases}</td><td><small>{time(r.first_activity_at)} → {time(r.last_activity_at)}</small></td></tr>)}</tbody></table></div></section>
  </>}
 </div>
}
