import { useEffect,useMemo,useState,type ReactNode } from 'react'
import { BarChart3,CalendarCheck2,Captions,CheckCheck,CircleDollarSign,MapPinCheck,PhoneCall,RefreshCw,Route,ShoppingBag,Users } from 'lucide-react'
import { Bar,BarChart,CartesianGrid,Legend,ResponsiveContainer,Tooltip,XAxis,YAxis } from 'recharts'
import { supabase } from '../lib/supabase'
import { KpiCard } from '../components/KpiCard'
import { exportXlsx } from '../lib/export'
import { exportScreenPdf } from '../lib/screenPdf'

const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Santo_Domingo'})
const zero={active_employees:0,planned_clients:0,visited_clients:0,received_clients:0,visit_purchase_clients:0,showroom_purchase_clients:0,call_purchase_clients:0,purchase_clients:0,visit_sales_amount:0,showroom_sales_amount:0,call_sales_amount:0,sales_amount:0,calls:0,calls_contacted:0,inbound_calls:0,outbound_calls:0,appointments:0,showroom_attended:0,prospects_captured:0,routes_started:0,routes_completed:0,route_execution_pct:0,call_contact_rate_pct:0,estimated_distance_m:0,gps_segments:0}
const money=(value:any)=>`RD$${Number(value||0).toLocaleString('es-DO',{maximumFractionDigits:2})}`
const firstName=(name:string)=>name?.trim().split(/\s+/)[0]||'—'
const ratioPct=(value:number,total:number)=>total?Math.round((value/total)*1000)/10:0
const coveragePct=(row:any)=>ratioPct(Number(row.visited_clients||0),Number(row.planned_clients||0))
const distanceKm=(meters?:number|string|null)=>`${(Number(meters||0)/1000).toLocaleString('es-DO',{minimumFractionDigits:1,maximumFractionDigits:2})} km`

export function DashboardV2(){
 const [global,setGlobal]=useState<any>(zero),[employees,setEmployees]=useState<any[]>([]),[stats,setStats]=useState({clients:0,geo:0,verified:0}),[busy,setBusy]=useState(true),[pdfBusy,setPdfBusy]=useState(false)
 const load=async()=>{setBusy(true);const day=today();const [{data:g},{data:e},{data:rm},{count:clients},{count:geo},{count:verified}]=await Promise.all([
  supabase.from('executive_daily_global_summary_v2').select('*').eq('day',day).maybeSingle(),
  supabase.from('executive_daily_employee_summary_v2').select('*').eq('day',day).order('operational_seconds',{ascending:false}),
  supabase.from('executive_daily_route_metrics').select('*').eq('day',day),
  supabase.from('clients').select('*',{count:'exact',head:true}),supabase.from('clients').select('*',{count:'exact',head:true}).not('latitude','is',null).not('longitude','is',null),supabase.from('clients').select('*',{count:'exact',head:true}).eq('geo_status','VERIFICADA'),
 ]);const metricMap=new Map((rm||[]).map((m:any)=>[m.employee_id,m]));const employeeRows=(e||[]).map((row:any)=>{const metric:any=metricMap.get(row.employee_id)||{};return {...row,purchase_clients:Number(row.purchase_clients_all??row.purchase_clients??0),sales_amount:Number(row.sales_amount_all??row.sales_amount??0),estimated_distance_m:Number(metric.estimated_distance_m||0),gps_segments:Number(metric.gps_segments||0)}});const distanceTotal=employeeRows.reduce((s:number,r:any)=>s+Number(r.estimated_distance_m||0),0),gpsSegments=employeeRows.reduce((s:number,r:any)=>s+Number(r.gps_segments||0),0);setGlobal({...zero,...(g||{}),estimated_distance_m:distanceTotal,gps_segments:gpsSegments});setEmployees(employeeRows);setStats({clients:clients||0,geo:geo||0,verified:verified||0});setBusy(false)}
 useEffect(()=>{void load();const onFocus=()=>void load();window.addEventListener('focus',onFocus);return()=>window.removeEventListener('focus',onFocus)},[])
 const vendors=useMemo(()=>employees.filter(e=>e.employee_type==='Vendedor').sort((a,b)=>Number(b.visited_clients||0)-Number(a.visited_clients||0)||Number(b.sales_amount||0)-Number(a.sales_amount||0)),[employees])
 const managers=useMemo(()=>employees.filter(e=>e.employee_type==='Gestor').sort((a,b)=>(Number(b.calls_contacted||0)+Number(b.showroom_attended||0))-(Number(a.calls_contacted||0)+Number(a.showroom_attended||0))||Number(b.sales_amount||0)-Number(a.sales_amount||0)),[employees])
 const vendorChart=useMemo(()=>vendors.slice(0,8).map(e=>({name:firstName(e.full_name),Planificados:e.planned_clients||0,Visitados:e.visited_clients||0,Compras:e.purchase_clients||0})),[vendors]),managerChart=useMemo(()=>managers.slice(0,8).map(e=>({name:firstName(e.full_name),Llamadas:e.calls||0,Contactados:e.calls_contacted||0,Showroom:e.showroom_attended||0,Compras:e.purchase_clients||0})),[managers])
 const reportRows=employees.filter(e=>['Vendedor','Gestor'].includes(e.employee_type)).map(e=>({Empleado:e.full_name,Cargo:e.job_title||'',Tipo:e.employee_type,Planificados:e.planned_clients,Visitados:e.visited_clients,'Cobertura real %':coveragePct(e),ComprasVisita:e.visit_purchase_clients||0,ComprasLlamada:e.call_purchase_clients||0,ComprasShowroom:e.showroom_purchase_clients||0,VentasVisita:Number(e.visit_sales_amount||0),VentasLlamada:Number(e.call_sales_amount||0),VentasShowroom:Number(e.showroom_sales_amount||0),VentasTotal:Number(e.sales_amount||0),Llamadas:e.calls,Entrantes:e.inbound_calls||0,Salientes:e.outbound_calls||0,Contactados:e.calls_contacted,Citas:e.appointments,Showroom:e.showroom_attended,Captaciones:e.prospects_captured,RutasCerradas:e.routes_completed}))
 const downloadPdf=async()=>{setPdfBusy(true);try{await exportScreenPdf('dashboard-workspace-pdf',`Resumen_Diario_${today()}.pdf',`Resumen Diario ${today()}`)}catch(e){alert(e instanceof Error?e.message:'No se pudo generar el PDF.')}finally{setPdfBusy(false)}}
 return <div className="page-stack executive-shell-v062">
  <div data-pdf-section="true" className="page-head"><div><span className="eyebrow">CENTRO DE OPERACIONES</span><h2>Resumen de hoy</h2><p>Lectura ejecutiva separada por función: operación de calle para Vendedores y CRM/Showroom para Gestores.</p></div><div data-pdf-exclude="true" className="button-row"><button className="secondary" onClick={()=>void load()}><RefreshCw size={17}/> Actualizar</button><button className="secondary" onClick={()=>void exportXlsx(`Resumen_Diario_${today()}`,reportRows)}>Excel</button><button className="secondary" disabled={pdfBusy} onClick={()=>void downloadPdf()}>{pdfBusy?'Generando PDF...':'PDF ejecutivo'}</button></div></div>
  <div data-pdf-section="true" className="executive-band"><div className="executive-brand-card"><img src="/logo-karaka.png" alt="Almacenes Karaka"/><div className="executive-brand-copy"><span>DIRECCIÓN COMERCIAL · CONTROL DIARIO</span><b>Almacenes Karaka</b><small>{new Date(`${today()}T12:00:00`).toLocaleDateString('es-DO',{weekday:'long',day:'2-digit',month:'long',year:'numeric'})} · información sincronizada con la operación registrada.</small></div></div><div className="executive-pulse"><span>Ventas registradas hoy</span><strong>{money(global.sales_amount)}</strong><small>{global.purchase_clients||0} compras · {global.visit_purchase_clients||0} calle · {global.call_purchase_clients||0} llamadas · {global.showroom_purchase_clients||0} showroom</small></div></div>
  <div data-pdf-section="true" className="kpi-grid"><KpiCard label="Clientes" value={stats.clients} sub={`${stats.geo} con GPS · ${stats.verified} verificadas`} Icon={Users}/><KpiCard label="Planificados" value={global.planned_clients||0} sub={`${global.route_execution_pct||0}% cobertura real`} Icon={Route}/><KpiCard label="Visitados" value={global.visited_clients||0} sub={`${global.received_clients||0} recibidos`} Icon={MapPinCheck}/><KpiCard label="Distancia GPS" value={distanceKm(global.estimated_distance_m)} sub={`${global.gps_segments||0} tramos · estimada`} Icon={Route}/><KpiCard label="Compraron" value={global.purchase_clients||0} sub={`${global.visit_purchase_clients||0} calle · ${global.call_purchase_clients||0} llamada · ${global.showroom_purchase_clients||0} showroom`} Icon={ShoppingBag}/><KpiCard label="Ventas" value={money(global.sales_amount)} sub={`${money(global.visit_sales_amount)} calle · ${money(global.call_sales_amount)} llamada · ${money(global.showroom_sales_amount)} showroom`} Icon={CircleDollarSign}/><KpiCard label="Llamadas" value={global.calls||0} sub={`${global.calls_contacted||0} contactadas · ${global.inbound_calls||0} entrantes · ${global.outbound_calls||0} salientes`} Icon={PhoneCall}/><KpiCard label="Citas" value={global.appointments||0} sub={`${global.showroom_attended||0} showroom`} Icon={CalendarCheck2}/><KpiCard label="Captaciones" value={global.prospects_captured||0} Icon={Captions}/><KpiCard label="Rutas cerradas" value={global.routes_completed||0} sub={`${global.routes_started||0} iniciadas`} Icon={CheckCheck}/></div>
  <div data-pdf-section="true" className="executive-chart-grid"><ChartPanel title="Vendedores · ejecución de calle" subtitle="Planificados, visitados y compras" loading={busy} empty={!vendorChart.length}><ResponsiveContainer width="100%" height={310}><BarChart data={vendorChart}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip/><Legend/><Bar dataKey="Planificados" fill="var(--chart-muted)" radius={[5,5,0,0]}/><Bar dataKey="Visitados" fill="var(--brand)" radius={[5,5,0,0]}/><Bar dataKey="Compras" fill="var(--success)" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></ChartPanel><ChartPanel title="Gestores · CRM y Showroom" subtitle="Llamadas, contactos, showroom y compras" loading={busy} empty={!managerChart.length}><ResponsiveContainer width="100%" height={310}><BarChart data={managerChart}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip/><Legend/><Bar dataKey="Llamadas" fill="var(--chart-muted)" radius={[5,5,0,0]}/><Bar dataKey="Contactados" fill="var(--brand)" radius={[5,5,0,0]}/><Bar dataKey="Showroom" fill="var(--warning)" radius={[5,5,0,0]}/><Bar dataKey="Compras" fill="var(--success)" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></ChartPanel></div>
  <div data-pdf-section="true" className="executive-section-grid"><TeamPanel title="Ranking de Vendedores" subtitle="Cobertura, distancia y resultado comercial" icon={<Route size={19}/>} count={vendors.length}>{vendors.length?vendors.slice(0,8).map((e,i)=><RankRow key={e.employee_id} row={e} position={i+1} vendor/>):<Empty text="Sin actividad de vendedores para esta fecha."/>}</TeamPanel><TeamPanel title="Ranking de Gestores" subtitle="Contacto, llamadas, showroom y conversión comercial" icon={<PhoneCall size={19}/>} count={managers.length}>{managers.length?managers.slice(0,8).map((e,i)=><RankRow key={e.employee_id} row={e} position={i+1}/>):<Empty text="Sin actividad de gestores para esta fecha."/>}</TeamPanel></div>
 </div>
}
function ChartPanel({title,subtitle,loading,empty,children}:{title:string;subtitle:string;loading:boolean;empty:boolean;children:ReactNode}){return <div className="panel executive-chart-card"><div className="panel-head"><div><b>{title}</b><span>{subtitle}</span></div><BarChart3 size={19}/></div>{loading?<div className="skeleton tall"/>:empty?<Empty text="Todavía no hay actividad registrada."/>:children}</div>}
function TeamPanel({title,subtitle,icon,count,children}:{title:string;subtitle:string;icon:ReactNode;count:number;children:ReactNode}){return <section className="panel executive-team-panel"><div className="executive-team-header"><div className="executive-team-title"><div className="executive-team-title-icon">{icon}</div><div><b>{title}</b><span>{subtitle}</span></div></div><span className="badge">{count} con registro</span></div><div className="executive-team-content"><div className="executive-rank-list">{children}</div></div></section>}
function RankRow({row,position,vendor=false}:{row:any;position:number;vendor?:boolean}){return <div className="executive-rank-row"><span className="executive-rank-position">{position}</span><div className="executive-rank-person"><b>{row.full_name}</b><small>{row.job_title||row.employee_type}{vendor?` · ${coveragePct(row)}% cobertura`:` · ${row.call_contact_rate_pct||0}% contacto`}</small></div><div className="executive-rank-kpis">{vendor?<><span><b>{row.visited_clients||0}/{row.planned_clients||0}</b> visitas</span><span><b>{distanceKm(row.estimated_distance_m)}</b> GPS</span></>:<><span><b>{row.calls_contacted||0}/{row.calls||0}</b> contactos</span><span><b>{row.call_purchase_clients||0}</b> compras llamada</span><span><b>{row.showroom_attended||0}</b> showroom</span></>}</div><div className="executive-rank-result"><strong>{money(row.sales_amount)}</strong><small>{row.purchase_clients||0} compras</small></div></div>}
function Empty({text}:{text:string}){return <div className="empty-state"><span>◇</span><b>{text}</b></div>}
