import { useEffect,useRef,useState } from 'react'
import L from 'leaflet'
import 'leaflet/dist/leaflet.css'
import { Crosshair, Navigation, Pentagon, Save, X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { googleMapsNavigation } from '../lib/geo'
import { useAuth } from '../context/AuthContext'
import type { Client } from '../types'
export function MapPage(){const {employee}=useAuth();const admin=['Administrador','Supervisor'].includes(employee?.app_role||'');const el=useRef<HTMLDivElement|null>(null);const mapRef=useRef<L.Map|null>(null);const layerRef=useRef<L.LayerGroup|null>(null);const drawLayer=useRef<L.Polygon|null>(null);const [clients,setClients]=useState<Client[]>([]);const [draw,setDraw]=useState(false);const [points,setPoints]=useState<[number,number][]>([]);const [zoneName,setZoneName]=useState('');const [saving,setSaving]=useState(false)
 useEffect(()=>{void supabase.from('clients').select('id,codempr,legal_name,v_cartera,g_cartera,province,municipality,latitude,longitude').not('latitude','is',null).not('longitude','is',null).limit(3000).then(({data})=>setClients((data||[]) as Client[]))},[])
 useEffect(()=>{if(!el.current||mapRef.current)return;const map=L.map(el.current,{zoomControl:false}).setView([18.7357,-70.1627],8);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'© OpenStreetMap'}).addTo(map);mapRef.current=map;layerRef.current=L.layerGroup().addTo(map);return()=>{map.remove();mapRef.current=null}},[])
 useEffect(()=>{const layer=layerRef.current;if(!layer)return;layer.clearLayers();clients.forEach(c=>{if(c.latitude==null||c.longitude==null)return;const marker=L.circleMarker([c.latitude,c.longitude],{radius:6,weight:2,color:'#fff',fillColor:'#c51f2f',fillOpacity:.88});const nav=googleMapsNavigation(c.latitude,c.longitude);marker.bindPopup(`<div class="map-popup"><b>${escapeHtml(c.legal_name)}</b><small>${escapeHtml(c.codempr)}</small><span>V: ${escapeHtml(c.v_cartera||'—')}</span><span>G: ${escapeHtml(c.g_cartera||'—')}</span>${nav?`<a target="_blank" href="${nav}">Navegar con Google Maps</a>`:''}</div>`);marker.addTo(layer)})},[clients])
 useEffect(()=>{const map=mapRef.current;if(!map)return;const click=(e:L.LeafletMouseEvent)=>{if(draw)setPoints(p=>[...p,[e.latlng.lat,e.latlng.lng]])};map.on('click',click);return()=>{map.off('click',click)}},[draw])
 useEffect(()=>{const map=mapRef.current;if(!map)return;if(drawLayer.current){drawLayer.current.remove();drawLayer.current=null}if(points.length>=2){drawLayer.current=L.polygon(points,{color:'#c51f2f',weight:3,fillOpacity:.12}).addTo(map)}},[points])
 const locate=()=>navigator.geolocation?.getCurrentPosition(p=>mapRef.current?.flyTo([p.coords.latitude,p.coords.longitude],15))
 const saveZone=async()=>{if(points.length<3||!zoneName.trim())return;setSaving(true);const ring=points.map(([lat,lng])=>[lng,lat]);ring.push(ring[0]);const geo={type:'Polygon',coordinates:[ring]};const {error}=await supabase.rpc('create_territory_polygon',{p_name:zoneName.trim(),p_geojson:geo,p_territory_type:'CAPTACION',p_notes:'Zona dibujada desde el mapa'});setSaving(false);if(error)alert(error.message);else{alert('Zona guardada');setPoints([]);setZoneName('');setDraw(false)}}
 return <div className="page-stack map-page"><div className="page-head"><div><span className="eyebrow">MAPA OPERATIVO</span><h2>Clientes y zonas</h2><p>{clients.length.toLocaleString()} clientes georreferenciados cargados en el mapa.</p></div><div className="button-row"><button className="secondary" onClick={locate}><Crosshair size={17}/> Mi ubicación</button>{admin&&<button className={draw?'primary':'secondary'} onClick={()=>{setDraw(!draw);setPoints([])}}><Pentagon size={17}/>{draw?'Dibujando zona':'Crear zona'}</button>}</div></div>{draw&&<div className="zone-toolbar"><b>Dibuja la zona tocando/clickeando el mapa</b><input placeholder="Nombre de la zona" value={zoneName} onChange={e=>setZoneName(e.target.value)}/><span>{points.length} puntos</span><button className="secondary" onClick={()=>setPoints([])}><X size={16}/> Limpiar</button><button className="primary" disabled={points.length<3||!zoneName.trim()||saving} onClick={()=>void saveZone()}><Save size={16}/>{saving?'Guardando...':'Guardar zona'}</button></div>}<div className="map-shell"><div ref={el} className="leaflet-map"/><div className="map-legend"><b>Leyenda</b><span><i className="dot client"/> Cliente</span><span><Navigation size={14}/> Pulse un cliente para navegar</span></div></div></div>}
function escapeHtml(s:string){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]||c))}
