import { useEffect,useMemo,useState } from 'react'
import { CalendarCheck,Coffee,DoorOpen,LogOut,Plus,Search,UserRoundCheck,Users,X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { useAuth } from '../context/AuthContext'
import { hasPermission } from '../lib/access'
import { ClientTypeFilter } from '../components/ClientTypeFilter'
import type { ClientTypeFilterValue } from '../components/ClientTypeFilter'

const dayStart=()=>{const d=new Date();d.setHours(0,0,0,0);return d}
const dayEnd=()=>{const d=dayStart();d.setDate(d.getDate()+1);return d}
const futureEnd=()=>{const d=dayStart();d.setDate(d.getDate()+8);return d}
const statusLabel=(v?:string)=>v==='ALMUERZO'?'Almuerzo':v==='EN_ATENCION'?'En atención':'Disponible'

export function ReceptionV2(){
 const {employee}=useAuth();const canCreateProspect=hasPermission(employee,'capture.create')
 const [appointments,setAppointments]=useState<any[]>([]),[entries,setEntries]=useState<any[]>([]),[clients,setClients]=useState<any[]>([]),[managers,setManagers]=useState<any[]>([]),[availability,setAvailability]=useState<any[]>([])
 const [clientType,setClientType]=useState<ClientTypeFilterValue>(''),[walkIn,setWalkIn]=useState(false),[busy,setBusy]=useState(false),[loadError,setLoadError]=useState('')
 const load=async()=>{
  setLoadError('');const start=dayStart().toISOString(),end=dayEnd().toISOString(),future=futureEnd().toISOString()
  const [a,e,c,m,av]=await Promise.all([
   supabase.from('appointments').select('*,clients(id,codempr,legal_name,client_type,phone1,mobile,contact_name,manager_employee_id),prospects(id,prospect_code,legal_name,phone,mobile),manager:employees!appointments_assigned_manager_id_fkey(id,full_name)').gte('appointment_at',start).lt('appointment_at',future).in('status',['CONFIRMADA','REPROGRAMADA','PROGRAMADA','ASISTIO','FINALIZADA']).order('appointment_at'),
   supabase.from('reception_entries').select('*,clients(codempr,legal_name,client_type),prospects(prospect_code,legal_name),manager:employees!reception_entries_assigned_manager_id_fkey(id,full_name),appointments(appointment_at,status)').gte('check_in_at',start).lt('check_in_at',end).order('check_in_at',{ascending:false}),
   supabase.from('clients').select('id,codempr,client_type,legal_name,contact_name,manager_employee_id,phone1,mobile,province,municipality').order('legal_name'),
   supabase.from('employees').select('id,full_name').eq('active',true).eq('employee_type','Gestor').order('full_name'),
   supabase.from('manager_reception_availability_v1').select('*').order('full_name'),
  ])
  const error=a.error||e.error||c.error||m.error||av.error;if(error)setLoadError(error.message)
  setAppointments(a.data||[]);setEntries(e.data||[]);setClients(c.data||[]);setManagers(m.data||[]);setAvailability(av.data||[])
 }
 useEffect(()=>{void load()},[])
 const filteredAppointments=useMemo(()=>appointments.filter(a=>!clientType||!a.client_id||a.clients?.client_type===clientType),[appointments,clientType]),filteredEntries=useMemo(()=>entries.filter(e=>!clientType||!e.client_id||e.clients?.client_type===clientType),[entries,clientType]),filteredClients=useMemo(()=>clients.filter(c=>!clientType||c.client_type===clientType),[clients,clientType])
 const entryByAppointment=useMemo(()=>new Map(filteredEntries.filter(e=>e.appointment_id).map(e=>[e.appointment_id,e])),[filteredEntries]);const todayKey=new Date().toDateString()
 const expected=filteredAppointments.filter(a=>a.appointment_at&&new Date(a.appointment_at).toDateString()===todayKey&&!entryByAppointment.has(a.id)&&!['ASISTIO','FINALIZADA'].includes(a.status)),upcoming=filteredAppointments.filter(a=>a.appointment_at&&new Date(a.appointment_at).toDateString()!==todayKey&&!entryByAppointment.has(a.id)&&['CONFIRMADA','REPROGRAMADA','PROGRAMADA'].includes(a.status))
 const inside=filteredEntries.filter(e=>!['SALIO','CANCELADO'].includes(e.status)),waiting=inside.filter(e=>e.status==='EN_ESPERA').length,inService=inside.filter(e=>e.status==='EN_ATENCION').length
 const arriveAppointment=async(row:any)=>{if(!employee?.id)return;if(!row.assigned_manager_id)return alert('Esta cita aún no tiene Gestor asignado.');setBusy(true);try{const {error}=await supabase.from('reception_entries').insert({appointment_id:row.id,client_id:row.client_id||null,prospect_id:row.prospect_id||null,visitor_type:'CITA',visitor_name:row.clients?.contact_name||row.clients?.legal_name||row.prospects?.legal_name||'Cita',company_name:row.clients?.legal_name||row.prospects?.legal_name||null,phone:row.clients?.mobile||row.clients?.phone1||row.prospects?.mobile||row.prospects?.phone||null,purpose:'Cita showroom',assigned_manager_id:row.assigned_manager_id,check_in_by:employee.id,status:'EN_ESPERA'});if(error)throw error;await supabase.from('appointments').update({status:'ASISTIO',attended_at:new Date().toISOString()}).eq('id',row.id);await load()}catch(e){alert(e instanceof Error?e.message:'No se pudo registrar la llegada')}finally{setBusy(false)}}
 const checkOut=async(entry:any)=>{if(!employee?.id)return;if(entry.status==='EN_ATENCION')return alert('El Gestor debe finalizar la atención antes de registrar la salida.');const {error}=await supabase.from('reception_entries').update({status:'SALIO',check_out_at:new Date().toISOString(),check_out_by:employee.id}).eq('id',entry.id);if(error)return alert(error.message);await load()}
 const nameOf=(r:any)=>r.visitor_name||r.clients?.legal_name||r.prospects?.legal_name||r.company_name||'Visitante'
 return <div className="page-stack">
  <div className="page-head"><div><span className="eyebrow">CONTROL DE PRESENCIA</span><h2>Recepción showroom</h2><p>Control de citas, llegadas, espera, atención y salida. Los casos comerciales siempre conservan un Gestor responsable.</p></div><div className="button-row"><ClientTypeFilter value={clientType} onChange={setClientType}/><button className="primary" onClick={()=>setWalkIn(true)}><Plus size={17}/> Llegada sin cita</button></div></div>
  <div className="kpi-grid"><Kpi label="Citas esperadas" value={expected.length} sub="pendientes de llegar hoy" Icon={CalendarCheck}/><Kpi label="Dentro" value={inside.length} sub="personas actualmente" Icon={DoorOpen}/><Kpi label="En espera" value={waiting} sub="pendientes de atención" Icon={Users}/><Kpi label="En atención" value={inService} sub="con un gestor" Icon={UserRoundCheck}/></div>
  <div className="panel"><div className="panel-head"><div><b>Disponibilidad de Gestores</b><span>Estado operativo y carga actual para asignaciones de Recepción.</span></div><button className="secondary compact" onClick={()=>void load()}>Actualizar</button></div><div className="cards-list">{availability.map(a=><div className="activity-card" key={a.employee_id}><div className="activity-icon">{a.availability_status==='ALMUERZO'?<Coffee/>:a.availability_status==='EN_ATENCION'?<UserRoundCheck/>:<Users/>}</div><div className="activity-main"><b>{a.full_name}</b><span>{statusLabel(a.availability_status)} · {a.waiting_clients||0} esperando · {a.active_clients||0} en atención</span><small>{a.availability_status==='ALMUERZO'&&a.lunch_started_at?`Salió a comer ${new Date(a.lunch_started_at).toLocaleTimeString('es-DO',{hour:'2-digit',minute:'2-digit'})}`:a.oldest_waiting_at?`Espera más antigua: ${new Date(a.oldest_waiting_at).toLocaleTimeString('es-DO',{hour:'2-digit',minute:'2-digit'})}`:'Sin espera actual'}</small></div><span className={`badge ${a.availability_status==='DISPONIBLE'?'success':''}`}>{statusLabel(a.availability_status)}</span></div>)}</div></div>
  {loadError&&<div className="panel"><b>Error cargando Recepción</b><span>{loadError}</span></div>}
  <div className="panel"><div className="panel-head"><div><b>Citas esperadas hoy</b><span>La cita ya fue confirmada por el Gestor. Recepción registra la llegada física.</span></div><span className="badge">{expected.length}</span></div><div className="cards-list">{expected.length===0&&<div className="empty-state"><b>No quedan citas confirmadas pendientes de llegada hoy.</b></div>}{expected.map(row=><div className="activity-card" key={row.id}><div className="activity-main"><b>{row.clients?.legal_name||row.prospects?.legal_name||'Cita'}</b><span>{row.appointment_at?new Date(row.appointment_at).toLocaleTimeString('es-DO',{hour:'2-digit',minute:'2-digit'}):''} · {row.clients?.client_type||'SIN TIPO'} · Gestor: {row.manager?.full_name||'Sin asignar'}</span><small>{row.status.replaceAll('_',' ')}{row.clients?.contact_name?` · ${row.clients.contact_name}`:''}</small></div><button className="primary compact" disabled={busy} onClick={()=>void arriveAppointment(row)}><DoorOpen size={15}/> Llegó</button></div>)}</div></div>
  <div className="panel"><div className="panel-head"><div><b>Próximas citas confirmadas</b><span>Vista anticipada de los próximos 7 días para planificar Recepción.</span></div><span className="badge">{upcoming.length}</span></div><div className="cards-list">{upcoming.length===0&&<div className="empty-state"><b>No hay citas confirmadas en los próximos 7 días.</b></div>}{upcoming.slice(0,30).map(row=><div className="activity-card" key={row.id}><div className="activity-main"><b>{row.clients?.legal_name||row.prospects?.legal_name||'Cita'}</b><span>{new Date(row.appointment_at).toLocaleString('es-DO')} · Gestor: {row.manager?.full_name||'Sin asignar'}</span><small>{row.status.replaceAll('_',' ')}</small></div></div>)}</div></div>
  <div className="panel"><div className="panel-head"><div><b>Movimientos de hoy</b><span>Entrada, atención y salida física se mantienen separadas.</span></div></div><div className="cards-list">{filteredEntries.length===0&&<div className="empty-state"><b>Aún no hay entradas registradas.</b></div>}{filteredEntries.map(row=><div className="activity-card" key={row.id}><div className="activity-main"><b>{nameOf(row)}</b><span>{row.company_name&&row.company_name!==row.visitor_name?`${row.company_name} · `:''}Llegó {new Date(row.check_in_at).toLocaleTimeString('es-DO',{hour:'2-digit',minute:'2-digit'})} · {row.manager?.full_name||'Sin gestor asignado'}</span><small>{row.purpose||row.visitor_type.replaceAll('_',' ')} · {row.status.replaceAll('_',' ')}{row.check_out_at?` · salió ${new Date(row.check_out_at).toLocaleTimeString('es-DO',{hour:'2-digit',minute:'2-digit'})}`:''}</small></div>{!['SALIO','CANCELADO'].includes(row.status)&&<button className="secondary compact" onClick={()=>void checkOut(row)}><LogOut size={15}/> Registrar salida</button>}</div>)}</div></div>
  {walkIn&&<WalkInModal clients={filteredClients} managers={managers} availability={availability} employeeId={employee?.id||''} canCreateProspect={canCreateProspect} onClose={()=>setWalkIn(false)} onSaved={async()=>{setWalkIn(false);await load()}}/>}
 </div>
}
function Kpi({label,value,sub,Icon}:{label:string;value:any;sub:string;Icon:any}){return <div className="kpi-card"><div className="kpi-icon"><Icon/></div><div><span>{label}</span><strong>{value}</strong><small>{sub}</small></div></div>}

function WalkInModal({clients,managers,availability,employeeId,canCreateProspect,onClose,onSaved}:{clients:any[];managers:any[];availability:any[];employeeId:string;canCreateProspect:boolean;onClose:()=>void;onSaved:()=>Promise<void>|void}){
 const [mode,setMode]=useState<'CLIENTE'|'NUEVO'>('CLIENTE'),[clientId,setClientId]=useState(''),[clientQuery,setClientQuery]=useState(''),[managerId,setManagerId]=useState(''),[visitorName,setVisitorName]=useState(''),[company,setCompany]=useState(''),[phone,setPhone]=useState(''),[purposeType,setPurposeType]=useState('Atención comercial'),[purposeDetail,setPurposeDetail]=useState(''),[notes,setNotes]=useState(''),[registerProspect,setRegisterProspect]=useState(false),[busy,setBusy]=useState(false)
 const selectedClient=clients.find(c=>c.id===clientId),commercial=['Atención comercial','Showroom / compra','Cotización'].includes(purposeType),managerState=(id:string)=>availability.find(a=>a.employee_id===id)
 const matches=useMemo(()=>{const n=clientQuery.trim().toLowerCase();if(!n||selectedClient)return[];return clients.filter(c=>`${c.legal_name||''} ${c.codempr||''} ${c.contact_name||''} ${c.phone1||''} ${c.mobile||''} ${c.province||''} ${c.municipality||''}`.toLowerCase().includes(n)).slice(0,20)},[clients,clientQuery,selectedClient])
 useEffect(()=>{if(!selectedClient)return;setManagerId(selectedClient.manager_employee_id||'');setCompany(selectedClient.legal_name||'');setVisitorName(selectedClient.contact_name||'');setPhone(selectedClient.mobile||selectedClient.phone1||'')},[selectedClient?.id])
 const chooseClient=(c:any)=>{setClientId(c.id);setClientQuery(c.legal_name)},clear=()=>{setClientId('');setClientQuery('');setManagerId('');setVisitorName('');setCompany('');setPhone('')}
 const save=async()=>{if(!employeeId)return;if(mode==='CLIENTE'&&!clientId)return alert('Busca y selecciona el cliente.');if(mode==='NUEVO'&&!visitorName.trim()&&!company.trim())return alert('Indica el nombre de la persona o empresa.');if(commercial&&!managerId)return alert('Toda llegada comercial debe quedar asignada a un Gestor.');setBusy(true);try{let prospectId:string|null=null;if(mode==='NUEVO'&&registerProspect){const {data,error}=await supabase.from('prospects').insert({legal_name:company.trim()||visitorName.trim(),contact_name:visitorName.trim()||null,phone:phone.trim()||null,captured_by_employee_id:employeeId,assigned_manager_id:managerId||null,status:'NUEVO',notes:`Identificado desde recepción. ${notes.trim()}`.trim()}).select('id').single();if(error)throw error;prospectId=data.id}const person=visitorName.trim()||selectedClient?.contact_name||selectedClient?.legal_name||company.trim(),companyName=mode==='CLIENTE'?selectedClient?.legal_name||null:company.trim()||null,purpose=purposeDetail.trim()||purposeType;const {error}=await supabase.from('reception_entries').insert({client_id:mode==='CLIENTE'?clientId:null,prospect_id:prospectId,visitor_type:mode==='CLIENTE'?'CLIENTE_SIN_CITA':prospectId?'PROSPECTO':'VISITANTE',visitor_name:person,company_name:companyName,phone:phone.trim()||selectedClient?.mobile||selectedClient?.phone1||null,purpose,assigned_manager_id:managerId||null,check_in_by:employeeId,status:managerId?'EN_ESPERA':'REGISTRADO',notes:notes||null});if(error)throw error;await onSaved()}catch(e){alert(e instanceof Error?e.message:'No se pudo registrar la llegada')}finally{setBusy(false)}}
 return <div className="modal-wrap"><button className="modal-backdrop" onClick={onClose}/><div className="modal large"><div className="modal-head"><div><span className="eyebrow">LLEGADA SIN CITA</span><h3>Registrar visitante</h3><p>Si la gestión es comercial debe quedar asociada a un Gestor.</p></div><button className="icon-btn" onClick={onClose}><X/></button></div><div className="tabs"><button className={mode==='CLIENTE'?'active':''} onClick={()=>{setMode('CLIENTE');clear()}}>Cliente existente</button><button className={mode==='NUEVO'?'active':''} onClick={()=>{setMode('NUEVO');clear()}}>Persona / empresa nueva</button></div><div className="form-grid">{mode==='CLIENTE'?<label className="span-2">Buscar cliente<div className="search-field"><Search/><input value={clientQuery} onChange={e=>{setClientQuery(e.target.value);if(clientId)setClientId('')}} placeholder="Nombre, código, teléfono, provincia..."/></div>{matches.length>0&&<div className="cards-list">{matches.map(c=><button className="activity-card" type="button" key={c.id} onClick={()=>chooseClient(c)}><div className="activity-main"><b>{c.legal_name}</b><span>{c.codempr} · {c.province||'—'} / {c.municipality||'—'}</span></div></button>)}</div>}</label>:<><label>Persona<input value={visitorName} onChange={e=>setVisitorName(e.target.value)}/></label><label>Empresa<input value={company} onChange={e=>setCompany(e.target.value)}/></label><label>Teléfono<input value={phone} onChange={e=>setPhone(e.target.value)}/></label>{canCreateProspect&&<label className="checkbox"><input type="checkbox" checked={registerProspect} onChange={e=>setRegisterProspect(e.target.checked)}/> Registrar como prospecto</label>}</>}
 <label>Motivo<select value={purposeType} onChange={e=>setPurposeType(e.target.value)}><option>Atención comercial</option><option>Showroom / compra</option><option>Cotización</option><option>Consulta general</option><option>Entrega documentación</option><option>Otro</option></select></label><label>Gestor responsable<select value={managerId} onChange={e=>setManagerId(e.target.value)} disabled={!!selectedClient?.manager_employee_id}><option value="">{commercial?'Selecciona Gestor':'Sin Gestor / consulta general'}</option>{managers.map(m=>{const s=managerState(m.id),disabled=!selectedClient?.manager_employee_id&&s?.availability_status==='ALMUERZO';return <option value={m.id} key={m.id} disabled={disabled}>{m.full_name} · {statusLabel(s?.availability_status)} · {s?.waiting_clients||0} esperando</option>})}</select><small>{selectedClient?.manager_employee_id?'Se conserva el Gestor oficial del cliente.':'Para clientes sin Gestor, Recepción ve disponibilidad y carga.'}</small></label><label className="span-2">Detalle del motivo<input value={purposeDetail} onChange={e=>setPurposeDetail(e.target.value)}/></label><label className="span-2">Observación<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><div className="modal-actions"><button className="secondary" onClick={onClose}>Cancelar</button><button className="primary" disabled={busy} onClick={()=>void save()}>{busy?'Registrando...':'Registrar llegada'}</button></div></div></div>
}
