import { useEffect,useMemo,useState } from 'react'
import { AlertTriangle,CalendarDays,CheckCircle2,Clock3,Download,FileSpreadsheet,FilterX,MapPinCheck,PhoneCall,Route,ShoppingBag,Users } from 'lucide-react'
import { Bar,BarChart,CartesianGrid,Legend,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis } from 'recharts'
import { supabase } from '../lib/supabase'
import { useAuth } from '../context/AuthContext'
import { profileForEmployee } from '../lib/access'
import { exportPdf,exportXlsx } from '../lib/export'
import '../styles/executive-v060.css'
import '../styles/journeys-reporting.css'

type PeriodMode='DAY'|'WEEK'|'MONTH'|'RANGE'
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Santo_Domingo'})
const ymd=(d:Date)=>d.toLocaleDateString('en-CA',{timeZone:'America/Santo_Domingo'})
const currentMonth=()=>today().slice(0,7)
const duration=(value?:number|null)=>{const total=Math.max(0,Math.round(Number(value||0)));const h=Math.floor(total/3600);const m=Math.round((total%3600)/60);return h?`${h} h ${m} min`:`${m} min`}
const money=(value?:number|string|null)=>new Intl.NumberFormat('es-DO',{style:'currency',currency:'DOP',maximumFractionDigits:0}).format(Number(value||0))
const pct=(a:number,b:number)=>b?Math.round((a/b)*1000)/10:0
const km=(m?:number|null)=>`${(Number(m||0)/1000).toLocaleString('es-DO',{minimumFractionDigits:1,maximumFractionDigits:1})} km`
const dayLabel=(d:string)=>new Date(`${d}T12:00:00`).toLocaleDateString('es-DO',{day:'2-digit',month:'short'})

function periodBounds(mode:PeriodMode,date:string,month:string,from:string,to:string){
  if(mode==='DAY')return {from:date,to:date}
  if(mode==='WEEK'){const base=new Date(`${date}T12:00:00`);const day=base.getDay()||7;const start=new Date(base);start.setDate(base.getDate()-day+1);const end=new Date(start);end.setDate(start.getDate()+6);return {from:ymd(start),to:ymd(end)}}
  if(mode==='MONTH'){const [y,m]=month.split('-').map(Number);return {from:ymd(new Date(y,m-1,1,12)),to:ymd(new Date(y,m,0,12))}}
  return {from:from||date,to:to||from||date}
}
const sum=(rows:any[],key:string)=>rows.reduce((acc,row)=>acc+Number(row[key]||0),0)

export function ReportsV2(){
  const {employee}=useAuth();const profile=profileForEmployee(employee);const executive=['Administrador','Supervisor'].includes(profile)
  const [mode,setMode]=useState<PeriodMode>(executive?'MONTH':'DAY');const [date,setDate]=useState(today());const [month,setMonth]=useState(currentMonth());const [from,setFrom]=useState(today());const [to,setTo]=useState(today())
  const [rawRows,setRawRows]=useState<any[]>([]);const [journeys,setJourneys]=useState<any[]>([]);const [employees,setEmployees]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('')
  const [employeeType,setEmployeeType]=useState('');const [employeeFilter,setEmployeeFilter]=useState('');const [selectedEmployee,setSelectedEmployee]=useState('')
  const range=useMemo(()=>periodBounds(mode,date,month,from,to),[mode,date,month,from,to])

  const load=async()=>{
    setLoading(true);setError('')
    let eQ=supabase.from('executive_daily_employee_summary').select('*').gte('day',range.from).lte('day',range.to).order('day')
    let rQ=supabase.from('executive_daily_route_metrics').select('*').gte('day',range.from).lte('day',range.to)
    let jQ=supabase.from('executive_route_journeys').select('*').gte('route_date',range.from).lte('route_date',range.to)
    if(!executive&&employee?.id){eQ=eQ.eq('employee_id',employee.id);rQ=rQ.eq('employee_id',employee.id);jQ=jQ.eq('employee_id',employee.id)}
    const [e,r,j,emps]=await Promise.all([eQ,rQ,jQ,executive?supabase.from('employees').select('id,full_name,job_title,employee_type').eq('active',true).in('employee_type',['Vendedor','Gestor']).order('full_name'):Promise.resolve({data:[],error:null}) as any])
    const err=e.error||r.error||j.error||emps.error;if(err)setError(err.message)
    const routeMap=new Map<string,any>();(r.data||[]).forEach((x:any)=>routeMap.set(`${x.employee_id}|${x.day}`,x))
    const journeyMap=new Map<string,any>();(j.data||[]).forEach((x:any)=>{const key=`${x.employee_id}|${x.route_date}`;const current=journeyMap.get(key)||{route_window_seconds:0,visit_seconds:0,incident_seconds:0,transit_wait_estimated_seconds:0};current.route_window_seconds+=Number(x.route_window_seconds||0);current.visit_seconds+=Number(x.visit_seconds||0);current.incident_seconds+=Number(x.incident_seconds||0);current.transit_wait_estimated_seconds+=Number(x.transit_wait_estimated_seconds||0);journeyMap.set(key,current)})
    const merged=(e.data||[]).map((row:any)=>{const key=`${row.employee_id}|${row.day}`;const rm=routeMap.get(key)||{};const jm=journeyMap.get(key);const vendor=row.employee_type==='Vendedor'&&jm;const visitSeconds=vendor?jm.visit_seconds:Number(row.visit_seconds||0);const incidentSeconds=vendor?jm.incident_seconds:Number(row.incident_seconds||0);const transit=vendor?jm.transit_wait_estimated_seconds:Number(row.transit_wait_estimated_seconds||0);const routeWindow=vendor?jm.route_window_seconds:Number(row.route_window_seconds||0);const operational=vendor?visitSeconds+incidentSeconds+transit+Number(row.call_estimated_seconds||0)+Number(row.showroom_seconds||0):Number(row.operational_seconds||0);return {...row,visit_seconds:visitSeconds,incident_seconds:incidentSeconds,transit_wait_estimated_seconds:transit,route_window_seconds:routeWindow,operational_seconds:operational,estimated_distance_m:Number(rm.estimated_distance_m||0),gps_segments:Number(rm.gps_segments||0)}})
    setRawRows(merged);setJourneys(j.data||[]);setEmployees(emps.data||[]);setSelectedEmployee(current=>current&&merged.some((x:any)=>x.employee_id===current)?current:(merged[0]?.employee_id||''));setLoading(false)
  }
  useEffect(()=>{void load()},[range.from,range.to,employee?.id,executive])
  useEffect(()=>{if(employeeFilter)setSelectedEmployee(employeeFilter)},[employeeFilter])

  const filteredRows=useMemo(()=>rawRows.filter(r=>(!employeeType||r.employee_type===employeeType)&&(!employeeFilter||r.employee_id===employeeFilter)),[rawRows,employeeType,employeeFilter])
  const filteredJourneys=useMemo(()=>journeys.filter(j=>(!employeeType||j.employee_type===employeeType)&&(!employeeFilter||j.employee_id===employeeFilter)),[journeys,employeeType,employeeFilter])
  const employeeOptions=useMemo(()=>employees.filter(e=>!employeeType||e.employee_type===employeeType),[employees,employeeType])
  const summary=useMemo(()=>{
    const planned=sum(filteredRows,'planned_clients'),visited=sum(filteredRows,'visited_clients'),resolved=sum(filteredRows,'resolved_clients'),calls=sum(filteredRows,'calls'),contacted=sum(filteredRows,'calls_contacted')
    const journeySeconds=filteredJourneys.reduce((s,j)=>s+Number(j.route_window_seconds||0),0);const visitSeconds=filteredJourneys.reduce((s,j)=>s+Number(j.visit_seconds||0),0);const transit=filteredJourneys.reduce((s,j)=>s+Number(j.transit_wait_estimated_seconds||0),0)
    return {planned,visited,resolved,coverage:pct(visited,planned),resolution:pct(resolved,planned),calls,contacted,contactRate:pct(contacted,calls),showroom:sum(filteredRows,'showroom_attended'),purchase:sum(filteredRows,'purchase_clients'),sales:sum(filteredRows,'sales_amount'),prospects:sum(filteredRows,'prospects_captured'),distance:sum(filteredRows,'estimated_distance_m'),gpsSegments:sum(filteredRows,'gps_segments'),operational:sum(filteredRows,'operational_seconds'),journeySeconds,visitSeconds,transit,incidents:sum(filteredRows,'incidents'),journeys:filteredJourneys.length,finished:filteredJourneys.filter(j=>['FINALIZADA','FINALIZADA_PARCIAL'].includes(j.derived_status)).length,expired:filteredJourneys.filter(j=>j.derived_status==='PENDIENTE_CIERRE').length,active:filteredJourneys.filter(j=>j.derived_status==='ACTIVA').length,activeDays:new Set(filteredRows.filter(r=>Number(r.operational_seconds||0)>0).map(r=>r.day)).size}
  },[filteredRows,filteredJourneys])

  const byEmployee=useMemo(()=>{const map=new Map<string,any>();filteredRows.forEach(r=>{const x=map.get(r.employee_id)||{employee_id:r.employee_id,full_name:r.full_name,job_title:r.job_title,employee_type:r.employee_type,planned_clients:0,visited_clients:0,resolved_clients:0,calls:0,calls_contacted:0,showroom_attended:0,purchase_clients:0,sales_amount:0,operational_seconds:0,estimated_distance_m:0,days:new Set<string>()};['planned_clients','visited_clients','resolved_clients','calls','calls_contacted','showroom_attended','purchase_clients','sales_amount','operational_seconds','estimated_distance_m'].forEach(k=>x[k]+=Number(r[k]||0));if(Number(r.operational_seconds||0)>0)x.days.add(r.day);map.set(r.employee_id,x)});return [...map.values()].map(x=>({...x,active_days:x.days.size,coverage_pct:pct(x.visited_clients,x.planned_clients),resolution_pct:pct(x.resolved_clients,x.planned_clients),contact_pct:pct(x.calls_contacted,x.calls)})).sort((a,b)=>b.operational_seconds-a.operational_seconds)},[filteredRows])

  const trend=useMemo(()=>{const map=new Map<string,any>();filteredRows.forEach(r=>{const x=map.get(r.day)||{day:r.day,Plan:0,Visitados:0,Resueltos:0,Ventas:0};x.Plan+=Number(r.planned_clients||0);x.Visitados+=Number(r.visited_clients||0);x.Resueltos+=Number(r.resolved_clients||0);x.Ventas+=Number(r.sales_amount||0);map.set(r.day,x)});return [...map.values()].sort((a,b)=>a.day.localeCompare(b.day)).map(x=>({...x,label:dayLabel(x.day),Cobertura:pct(x.Visitados,x.Plan)}))},[filteredRows])
  const selectedDaily=useMemo(()=>filteredRows.filter(r=>r.employee_id===selectedEmployee).sort((a,b)=>a.day.localeCompare(b.day)),[filteredRows,selectedEmployee])

  const clear=()=>{setEmployeeType('');setEmployeeFilter('')}
  const report=byEmployee.map(r=>({Colaborador:r.full_name,Tipo:r.employee_type,'Días activos':r.active_days,Planificados:r.planned_clients,Visitados:r.visited_clients,'Cobertura %':r.coverage_pct,Resueltos:r.resolved_clients,'Cierre operativo %':r.resolution_pct,Llamadas:r.calls,Contactados:r.calls_contacted,'Contacto %':r.contact_pct,Showroom:r.showroom_attended,'Clientes con compra':r.purchase_clients,Ventas:r.sales_amount,'Horas operativas':duration(r.operational_seconds),'Distancia GPS':km(r.estimated_distance_m)}))
  const dailyReport=selectedDaily.map(r=>({Fecha:r.day,Planificados:r.planned_clients,Visitados:r.visited_clients,'Cobertura %':pct(Number(r.visited_clients||0),Number(r.planned_clients||0)),Resueltos:r.resolved_clients,Llamadas:r.calls,Contactados:r.calls_contacted,Showroom:r.showroom_attended,Compras:r.purchase_clients,Ventas:r.sales_amount,'Tiempo operativo':duration(r.operational_seconds),'Distancia GPS':km(r.estimated_distance_m)}))

  return <div className="page-stack executive-report period-report">
    <div className="page-head"><div><span className="eyebrow">{executive?'INTELIGENCIA COMERCIAL · MULTIPERÍODO':'MI DESEMPEÑO'}</span><h2>{executive?'Reporte ejecutivo':'Mi reporte'}</h2><p>{executive?'Analiza días, semanas, meses o rangos completos sin promediar porcentajes de forma incorrecta.':'Consulta tu actividad y resultados por el período que necesites.'}</p></div><div className="button-row"><button className="secondary" disabled={!byEmployee.length} onClick={()=>void exportXlsx(`Reporte_${range.from}_${range.to}`,report)}><FileSpreadsheet size={17}/> Excel</button><button className="secondary" disabled={!byEmployee.length} onClick={()=>exportPdf(`Reporte ejecutivo ${range.from} - ${range.to}`,report)}><Download size={17}/> PDF</button></div></div>

    <section className="panel report-filter-panel"><div className="report-filter-grid"><label>Período<select value={mode} onChange={e=>setMode(e.target.value as PeriodMode)}><option value="DAY">Día</option><option value="WEEK">Semana</option><option value="MONTH">Mes</option><option value="RANGE">Rango</option></select></label>{mode==='DAY'&&<label>Fecha<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>}{mode==='WEEK'&&<label>Semana de<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>}{mode==='MONTH'&&<label>Mes<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label>}{mode==='RANGE'&&<><label>Desde<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Hasta<input type="date" min={from} value={to} onChange={e=>setTo(e.target.value)}/></label></>}{executive&&<><label>Tipo colaborador<select value={employeeType} onChange={e=>{setEmployeeType(e.target.value);setEmployeeFilter('')}}><option value="">Todos</option><option value="Vendedor">Vendedores</option><option value="Gestor">Gestores</option></select></label><label>Colaborador<select value={employeeFilter} onChange={e=>setEmployeeFilter(e.target.value)}><option value="">Todos los colaboradores</option>{employeeOptions.map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select></label></>}</div><div className="journey-filter-foot"><span>{range.from} → {range.to} · {filteredRows.length} registros diarios</span>{executive&&<button className="secondary compact" onClick={clear}><FilterX size={15}/> Limpiar filtros</button>}</div></section>

    {error&&<div className="panel journey-alert danger"><AlertTriangle/><div><b>No fue posible cargar el reporte</b><span>{error}</span></div></div>}
    {loading?<div className="panel empty-state"><b>Calculando indicadores del período...</b></div>:<>
      <div className="period-kpi-grid"><ReportKpi icon={<CalendarDays/>} label="Jornadas" value={summary.journeys} note={`${summary.finished} finalizadas · ${summary.expired} pendientes cierre`}/><ReportKpi icon={<MapPinCheck/>} label="Cobertura real" value={`${summary.coverage}%`} note={`${summary.visited}/${summary.planned} visitados`}/><ReportKpi icon={<CheckCircle2/>} label="Cierre operativo" value={`${summary.resolution}%`} note={`${summary.resolved}/${summary.planned} con resultado`}/><ReportKpi icon={<Route/>} label="Distancia GPS" value={km(summary.distance)} note={`${summary.gpsSegments} tramos · estimada`}/><ReportKpi icon={<Clock3/>} label="Tiempo operativo" value={duration(summary.operational)} note={`${summary.activeDays} día(s) con actividad`}/><ReportKpi icon={<PhoneCall/>} label="Contacto" value={`${summary.contactRate}%`} note={`${summary.contacted}/${summary.calls} llamadas`}/><ReportKpi icon={<ShoppingBag/>} label="Clientes con compra" value={summary.purchase} note={`${summary.showroom} atenciones showroom`}/><ReportKpi icon={<ShoppingBag/>} label="Monto vendido" value={money(summary.sales)} note={`${summary.prospects} captaciones`}/></div>

      {summary.expired>0&&<div className="panel journey-alert warning"><AlertTriangle/><div><b>{summary.expired} jornada(s) del período están pendientes de cierre.</b><span>Sus ventanas de jornada se limitan al día operativo para evitar que el reporte acumule horas indefinidamente. Revísalas desde Jornadas.</span></div></div>}

      <div className="executive-chart-grid"><Chart title="Plan vs ejecución por día" subtitle="Los porcentajes del período se calculan con totales reales" empty={!trend.length}><ResponsiveContainer width="100%" height={290}><BarChart data={trend}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label"/><YAxis allowDecimals={false}/><Tooltip/><Legend/><Bar dataKey="Plan" fill="var(--chart-muted)" radius={[4,4,0,0]}/><Bar dataKey="Visitados" fill="var(--brand)" radius={[4,4,0,0]}/><Bar dataKey="Resueltos" fill="var(--success)" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></Chart><Chart title="Cobertura diaria" subtitle={`Cobertura acumulada del período: ${summary.coverage}%`} empty={!trend.length}><ResponsiveContainer width="100%" height={290}><LineChart data={trend}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label"/><YAxis domain={[0,100]} unit="%"/><Tooltip/><Line type="monotone" dataKey="Cobertura" stroke="var(--brand)" strokeWidth={3} dot={{r:3}}/></LineChart></ResponsiveContainer></Chart></div>

      <section className="panel period-team-panel"><div className="panel-head"><div><b>{executive?'Desempeño por colaborador':'Resumen del período'}</b><span>Cobertura = visitados acumulados / planificados acumulados.</span></div><span>{byEmployee.length}</span></div><div className="journey-table-wrap"><table className="journey-table"><thead><tr><th>Colaborador</th><th>Días</th><th>Plan</th><th>Visitados</th><th>Cobertura</th><th>Cierre op.</th><th>Llamadas</th><th>Compras</th><th>Ventas</th><th>GPS</th><th></th></tr></thead><tbody>{byEmployee.map(r=><tr key={r.employee_id} className={selectedEmployee===r.employee_id?'selected-report-row':''} onClick={()=>setSelectedEmployee(r.employee_id)}><td><b>{r.full_name}</b><small>{r.job_title||r.employee_type}</small></td><td>{r.active_days}</td><td>{r.planned_clients}</td><td>{r.visited_clients}</td><td><b>{r.coverage_pct}%</b></td><td>{r.resolution_pct}%</td><td>{r.calls}</td><td>{r.purchase_clients}</td><td>{money(r.sales_amount)}</td><td>{km(r.estimated_distance_m)}</td><td>›</td></tr>)}</tbody></table>{!byEmployee.length&&<div className="empty-state"><Users/><b>Sin actividad para el período y filtros seleccionados.</b></div>}</div></section>

      {selectedDaily.length>0&&<section className="panel period-daily-panel"><div className="panel-head"><div><span className="eyebrow">DETALLE DIARIO</span><b>{selectedDaily[0].full_name}</b><span>{selectedDaily.length} día(s) con registro dentro del período.</span></div><div className="button-row"><button className="secondary compact" onClick={()=>void exportXlsx(`Detalle_${selectedDaily[0].full_name}_${range.from}_${range.to}`,dailyReport)}>Excel detalle</button><button className="secondary compact" onClick={()=>exportPdf(`Detalle ${selectedDaily[0].full_name} ${range.from} - ${range.to}`,dailyReport)}>PDF detalle</button></div></div><div className="daily-detail-grid">{selectedDaily.map(r=><div className="daily-detail-card" key={`${r.employee_id}-${r.day}`}><div><b>{new Date(`${r.day}T12:00:00`).toLocaleDateString('es-DO',{weekday:'short',day:'2-digit',month:'short'})}</b><span>{r.planned_clients||0} plan · {r.visited_clients||0} visitas</span></div><strong>{pct(Number(r.visited_clients||0),Number(r.planned_clients||0))}%</strong><small>{duration(r.operational_seconds)} · {km(r.estimated_distance_m)} · {money(r.sales_amount)}</small></div>)}</div></section>}
    </>}
  </div>
}

function ReportKpi({icon,label,value,note}:{icon:React.ReactNode;label:string;value:React.ReactNode;note:string}){return <div className="panel period-kpi"><div className="journey-kpi-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></div>}
function Chart({title,subtitle,empty,children}:{title:string;subtitle:string;empty:boolean;children:React.ReactNode}){return <section className="panel executive-chart-card"><div className="panel-head"><div><b>{title}</b><span>{subtitle}</span></div></div>{empty?<div className="empty-state"><b>Sin datos para graficar.</b></div>:children}</section>}
