import { useEffect,useMemo,useState } from 'react'
import { Ban,CheckCircle2,MapPin,Navigation,Play,RefreshCw,Square,X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { currentPosition,googleMapsNavigation } from '../lib/geo'
import { useAuth } from '../context/AuthContext'
import type { Employee } from '../types'
import { exportPdf,exportXlsx } from '../lib/export'
export function Routes(){const {employee}=useAuth();const [plans,setPlans]=useState<any[]>([]);const [employees,setEmployees]=useState<Employee[]>([]);const [selected,setSelected]=useState<any|null>(null);const [stops,setStops]=useState<any[]>([]);const [session,setSession]=useState<any|null>(null);const [busy,setBusy]=useState(false);const [exceptionStop,setExceptionStop]=useState<any|null>(null)
 const load=async()=>{const [{data:p},{data:e}]=await Promise.all([supabase.from('route_plans').select('*').order('route_date',{ascending:false}).limit(100),supabase.from('employees').select('*')]);setPlans(p||[]);setEmployees((e||[]) as Employee[]);if(selected){const {data:s}=await supabase.from('route_stops').select('*,clients(id,codempr,legal_name,latitude,longitude,municipality,phone1)').eq('route_plan_id',selected.id).order('stop_order');setStops(s||[]);const {data:rs}=await supabase.from('route_sessions').select('*').eq('route_plan_id',selected.id).eq('employee_id',employee?.id||'').is('ended_at',null).maybeSingle();setSession(rs||null)}}
 useEffect(()=>{void load()},[selected?.id,employee?.id])
 const empName=(id:string)=>employees.find(e=>e.id===id)?.full_name||'—';const mine=selected?.employee_id===employee?.id
 const start=async()=>{if(!selected||!mine)return;setBusy(true);try{const p=await currentPosition();const {data,error}=await supabase.from('route_sessions').insert({route_plan_id:selected.id,employee_id:employee!.id,session_date:selected.route_date,session_type:selected.plan_type,status:'ACTIVA',start_latitude:p.latitude,start_longitude:p.longitude,start_accuracy_m:p.accuracy}).select().single();if(error)throw error;setSession(data);await supabase.from('route_plans').update({status:'EN_CURSO'}).eq('id',selected.id)}catch(e){alert(e instanceof Error?e.message:'Error')}finally{setBusy(false);void load()}}
 const end=async()=>{if(!session)return;setBusy(true);try{const p=await currentPosition();const {error}=await supabase.from('route_sessions').update({ended_at:new Date().toISOString(),end_latitude:p.latitude,end_longitude:p.longitude,end_accuracy_m:p.accuracy,status:'FINALIZADA'}).eq('id',session.id);if(error)throw error;await supabase.from('route_plans').update({status:'FINALIZADA'}).eq('id',selected.id);setSession(null)}catch(e){alert(e instanceof Error?e.message:'Error')}finally{setBusy(false);void load()}}
 const startVisit=async(stop:any)=>{if(!session||!mine)return alert('Debes iniciar la ruta primero');setBusy(true);try{const p=await currentPosition();const {data,error}=await supabase.from('visits').insert({route_session_id:session.id,route_stop_id:stop.id,client_id:stop.client_id,employee_id:employee!.id,visit_kind:'CLIENTE',planned:true,started_at:new Date().toISOString(),start_latitude:p.latitude,start_longitude:p.longitude,start_accuracy_m:p.accuracy}).select().single();if(error)throw error;await supabase.from('route_stops').update({status:'EN_VISITA',visit_id:data.id}).eq('id',stop.id);alert('Visita iniciada. Finalízala desde el módulo Visitas.')}catch(e){alert(e instanceof Error?e.message:'Error')}finally{setBusy(false);void load()}}
 const report=stops.map(s=>({Orden:s.stop_order,Cliente:s.clients?.legal_name||'',Codigo:s.clients?.codempr||'',Municipio:s.clients?.municipality||'',Prioridad:s.priority,Estado:s.status,Motivo:s.reason_not_visited||''}))
 return <div className="page-stack"><div className="page-head"><div><span className="eyebrow">PLAN VS EJECUCIÓN</span><h2>Rutas asignadas</h2><p>Consulta las rutas de todo el equipo y ejecuta las tuyas desde el teléfono.</p></div><button className="secondary" onClick={()=>void load()}><RefreshCw size={17}/> Actualizar</button></div><div className="split-view"><div className="panel route-list">{plans.map(p=><button key={p.id} className={`route-card ${selected?.id===p.id?'selected':''}`} onClick={()=>setSelected(p)}><div><b>{empName(p.employee_id)}</b><span>{p.route_date} · {p.plan_type==='CAPTACION'?'Captación':'Visitas'}</span></div><span className={`status ${p.status?.toLowerCase()}`}>{p.status}</span></button>)}</div><div className="panel route-detail">{!selected?<div className="empty-state"><MapPin/><b>Selecciona una ruta</b></div>:<><div className="panel-head"><div><b>{empName(selected.employee_id)}</b><span>{selected.route_date} · {selected.title}</span></div><div className="button-row"><button className="secondary" onClick={()=>void exportXlsx(`Ruta_${selected.route_date}`,report)}>Excel</button><button className="secondary" onClick={()=>exportPdf(`Ruta ${selected.route_date}`,report)}>PDF</button></div></div>{mine&&<div className="route-actions">{!session?<button className="primary" disabled={busy} onClick={()=>void start()}><Play size={18}/> Iniciar ruta</button>:<><span className="live-pill"><i/> Ruta activa desde {new Date(session.started_at).toLocaleTimeString('es-DO',{hour:'2-digit',minute:'2-digit'})}</span><button className="danger" disabled={busy} onClick={()=>void end()}><Square size={18}/> Finalizar ruta</button></>}</div>}<div className="stop-list">{stops.length?stops.map(s=><div className="stop-card" key={s.id}><span className="stop-order">{s.stop_order}</span><div className="stop-main"><b>{s.clients?.legal_name||'Parada'}</b><span>{s.clients?.codempr} · {s.clients?.municipality||''}</span><small>{s.status}</small></div><div className="row-actions">{googleMapsNavigation(s.clients?.latitude,s.clients?.longitude)&&<a className="icon-btn" target="_blank" rel="noreferrer" href={googleMapsNavigation(s.clients?.latitude,s.clients?.longitude)!}><Navigation size={17}/></a>}{mine&&session&&s.status!=='VISITADO'&&<><button className="primary compact" disabled={busy||s.status==='EN_VISITA'||s.status==='NO_VISITADO'} onClick={()=>void startVisit(s)}>{s.status==='EN_VISITA'?<CheckCircle2 size={16}/>:<Play size={16}/>} {s.status==='EN_VISITA'?'En visita':'Visitar'}</button>{s.status!=='EN_VISITA'&&s.status!=='NO_VISITADO'&&<button className="secondary compact" onClick={()=>setExceptionStop(s)}><Ban size={16}/> No realizada</button>}</>}</div></div>):<div className="empty-state"><b>Jornada territorial sin paradas predefinidas.</b></div>}</div></>}</div></div>{exceptionStop&&<RouteException stop={exceptionStop} onClose={()=>setExceptionStop(null)} onSaved={()=>{setExceptionStop(null);void load()}}/>}</div>}

function RouteException({stop,onClose,onSaved}:{stop:any;onClose:()=>void;onSaved:()=>void}){const reasons=[['CLIENTE_CERRADO','Cliente cerrado'],['NO_ESTABA_RESPONSABLE','No estaba el responsable'],['REPROGRAMADA','Visita reprogramada'],['DIRECCION_INCORRECTA','Dirección incorrecta'],['NO_LOCALIZADO','Cliente no localizado'],['CAMBIO_RUTA','Cambio de ruta'],['OTRO','Otro']];const [reason,setReason]=useState(reasons[0][0]);const [notes,setNotes]=useState('');const [busy,setBusy]=useState(false);const save=async()=>{setBusy(true);const label=reasons.find(r=>r[0]===reason)?.[1]||reason;const {error}=await supabase.from('route_stops').update({status:'NO_VISITADO',exception_reason_code:reason,reason_not_visited:label,notes:notes||null}).eq('id',stop.id);setBusy(false);if(error)alert(error.message);else onSaved()};return <div className="modal-wrap"><button className="modal-backdrop" onClick={onClose}/><div className="modal"><div className="modal-head"><div><span className="eyebrow">EXCEPCIÓN DE RUTA</span><h3>{stop.clients?.legal_name||'Cliente'}</h3></div><button className="icon-btn" onClick={onClose}><X/></button></div><div className="form-grid"><label className="span-2">Motivo<select value={reason} onChange={e=>setReason(e.target.value)}>{reasons.map(([code,label])=><option value={code} key={code}>{label}</option>)}</select></label><label className="span-2">Observación<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Detalle opcional..."/></label></div><div className="modal-actions"><button className="secondary" onClick={onClose}>Cancelar</button><button className="danger" disabled={busy} onClick={()=>void save()}>{busy?'Guardando...':'Registrar no realizada'}</button></div></div></div>}

