import { useEffect,useMemo,useState,type CSSProperties } from 'react'
import { AlertTriangle,CheckCircle2,Clock3,Eye,FilterX,Layers3,LocateFixed,MapPin,Navigation,Pause,Play,RefreshCw,RotateCcw,Route,ShieldCheck,SkipBack,SkipForward,Target,UsersRound } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { MetricCard } from '../components/MetricCard'
import { LiveTrackingMap } from '../components/LiveTrackingMap'
import type { TrackingEvent,TrackingSnapshot,TrackingStop } from '../components/LiveTrackingMap'
import { ACTIVE_TRACKING_STATUSES,formatAccuracy,formatDistance,geoClassFor,geoClassLabel,geoClassTone,gpsQualityClass,gpsQualityLabel,routeColorFor,type TrackingGeoClass,type TrackingMapMode } from '../lib/trackingGeo'
import '../styles/tracking.css'

const rdDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Santo_Domingo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const duration=(seconds=0)=>{const s=Math.max(0,Math.round(Number(seconds)||0)),h=Math.floor(s/3600),m=Math.floor((s%3600)/60);return h?`${h} h ${m} min`:`${m} min`}
const time=(value?:string|null)=>value?new Date(value).toLocaleTimeString('es-DO',{hour:'2-digit',minute:'2-digit'}):'—'
const age=(minutes?:number|null)=>minutes==null?'Sin registro':minutes<1?'Ahora':minutes<60?`Hace ${minutes} min`:`Hace ${Math.floor(minutes/60)} h ${minutes%60} min`
const pct=(n:number,d:number)=>d?Math.round(n/d*1000)/10:0
const uniq=(values:Array<string|null|undefined>)=>Array.from(new Set(values.filter(Boolean) as string[])).sort((a,b)=>a.localeCompare(b,'es'))
const statusLabel=(s:string)=>({EN_VISITA:'En visita',EN_TRASLADO:'En traslado',EVENTUALIDAD:'Eventualidad',PENDIENTE_CIERRE:'Pendiente cierre',PLANIFICADA:'Planificada',FINALIZADA:'Finalizada',NO_EJECUTADA:'No ejecutada'} as Record<string,string>)[s]||s.replaceAll('_',' ')
const statusClass=(s:string)=>s.toLowerCase().replaceAll('_','-')
const eventTypeLabel=(s:string)=>({ROUTE_START:'Inicio ruta',VISIT_START:'Llegada cliente',VISIT_END:'Salida cliente',INCIDENT_START:'Inicio eventualidad',INCIDENT_END:'Fin eventualidad',ROUTE_END:'Cierre ruta'} as Record<string,string>)[s]||s.replaceAll('_',' ')
const eventKindClass=(s:string)=>s.toLowerCase()
const eventSort=(a:TrackingEvent,b:TrackingEvent)=>new Date(a.event_at).getTime()-new Date(b.event_at).getTime()

type RouteFilter=''|'ACTIVE'|'FINISHED'|'WITH_GPS'|'ANOMALY'

export function Tracking(){
 const today=rdDate()
 const[date,setDate]=useState(today),[snapshots,setSnapshots]=useState<TrackingSnapshot[]>([]),[stops,setStops]=useState<TrackingStop[]>([]),[events,setEvents]=useState<TrackingEvent[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const[vendor,setVendor]=useState(''),[status,setStatus]=useState(''),[freshness,setFreshness]=useState(''),[region,setRegion]=useState(''),[province,setProvince]=useState(''),[municipality,setMunicipality]=useState(''),[onlyGps,setOnlyGps]=useState(false),[showStops,setShowStops]=useState(true),[autoRefresh,setAutoRefresh]=useState(true)
 const[routeFilter,setRouteFilter]=useState<RouteFilter>(''),[eventType,setEventType]=useState(''),[gpsQuality,setGpsQuality]=useState(''),[geoValidation,setGeoValidation]=useState<TrackingGeoClass|''>('')
 const[viewMode,setViewMode]=useState<TrackingMapMode>('LIVE'),[isolateSelected,setIsolateSelected]=useState(false),[selectedEventId,setSelectedEventId]=useState('')
 const[selectedPlan,setSelectedPlan]=useState(''),[playbackIndex,setPlaybackIndex]=useState(-1),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1),[lastRefresh,setLastRefresh]=useState<Date|null>(null)

 const load=async()=>{setLoading(true);setError('');const[a,b,c]=await Promise.all([supabase.from('executive_tracking_snapshot_v1').select('*').eq('route_date',date).order('full_name'),supabase.from('executive_tracking_stops_v1').select('*').eq('route_date',date).order('employee_id').order('stop_order'),supabase.from('executive_tracking_events_v1').select('*').eq('route_date',date).order('event_at',{ascending:true})]);const err=a.error||b.error||c.error;if(err)setError(err.message);setSnapshots((a.data||[]) as TrackingSnapshot[]);setStops((b.data||[]) as TrackingStop[]);setEvents(((c.data||[]) as TrackingEvent[]).sort(eventSort));setLastRefresh(new Date());setLoading(false)}
 useEffect(()=>{void load()},[date])
 useEffect(()=>{if(!autoRefresh||date!==today)return;const id=window.setInterval(()=>void load(),30000);return()=>window.clearInterval(id)},[autoRefresh,date,today])

 const vendors=useMemo(()=>{const byId=new Map<string,string>();snapshots.forEach(s=>byId.set(s.employee_id,s.full_name));return Array.from(byId.entries()).sort((a,b)=>a[1].localeCompare(b[1],'es'))},[snapshots])
 const regions=useMemo(()=>uniq(snapshots.flatMap(s=>s.official_regions||[])),[snapshots]),provinces=useMemo(()=>uniq(snapshots.filter(s=>!region||(s.official_regions||[]).includes(region)).flatMap(s=>s.official_provinces||[])),[snapshots,region]),municipalities=useMemo(()=>uniq(snapshots.filter(s=>(!region||(s.official_regions||[]).includes(region))&&(!province||(s.official_provinces||[]).includes(province))).flatMap(s=>s.official_municipalities||[])),[snapshots,region,province])
 const eventsByPlan=useMemo(()=>{const map=new Map<string,TrackingEvent[]>();events.forEach(e=>{const list=map.get(e.route_plan_id)||[];list.push(e);map.set(e.route_plan_id,list)});return map},[events])
 const eventMatchesAdvanced=(e:TrackingEvent)=>{if(eventType&&e.event_type!==eventType)return false;if(gpsQuality==='RELIABLE'&&!e.has_gps)return false;if(gpsQuality&&gpsQuality!=='RELIABLE'&&e.gps_quality!==gpsQuality)return false;if(geoValidation&&geoClassFor(e)!==geoValidation)return false;return true}
 const advancedActive=Boolean(eventType||gpsQuality||geoValidation)

 const filtered=useMemo(()=>snapshots.filter(s=>{if(vendor&&s.employee_id!==vendor)return false;if(status&&s.tracking_status!==status)return false;if(date===today&&freshness&&s.freshness_status!==freshness)return false;if(region&&!(s.official_regions||[]).includes(region))return false;if(province&&!(s.official_provinces||[]).includes(province))return false;if(municipality&&!(s.official_municipalities||[]).includes(municipality))return false;if(onlyGps&&(s.last_latitude==null||s.last_longitude==null))return false;const planEvents=eventsByPlan.get(s.route_plan_id)||[];if(routeFilter==='ACTIVE'&&!ACTIVE_TRACKING_STATUSES.includes(s.tracking_status))return false;if(routeFilter==='FINISHED'&&!['FINALIZADA','NO_EJECUTADA'].includes(s.tracking_status))return false;if(routeFilter==='WITH_GPS'&&!planEvents.some(e=>e.has_gps))return false;if(routeFilter==='ANOMALY'&&!planEvents.some(e=>Boolean(e.location_exception_code)))return false;if(advancedActive&&!planEvents.some(eventMatchesAdvanced))return false;return true}),[snapshots,vendor,status,freshness,region,province,municipality,onlyGps,date,today,eventsByPlan,routeFilter,advancedActive,eventType,gpsQuality,geoValidation])
 const visiblePlanIds=useMemo(()=>new Set(filtered.map(s=>s.route_plan_id)),[filtered])
 const visibleStops=useMemo(()=>stops.filter(s=>visiblePlanIds.has(s.route_plan_id)),[stops,visiblePlanIds])
 const visibleEvents=useMemo(()=>events.filter(e=>visiblePlanIds.has(e.route_plan_id)),[events,visiblePlanIds])
 const matchingEvents=useMemo(()=>visibleEvents.filter(eventMatchesAdvanced),[visibleEvents,eventType,gpsQuality,geoValidation])
 const selectedSnapshot=useMemo(()=>filtered.find(s=>s.route_plan_id===selectedPlan)||null,[filtered,selectedPlan])
 const employeeIds=useMemo(()=>Array.from(new Set(filtered.map(s=>s.employee_id))).sort(),[filtered])
 const mapSnapshots=useMemo(()=>{const byEmployee=new Map<string,TrackingSnapshot>();filtered.forEach(s=>{const current=byEmployee.get(s.employee_id),stamp=s.last_event_at?new Date(s.last_event_at).getTime():-1,currentStamp=current?.last_event_at?new Date(current.last_event_at).getTime():-1;if(!current||stamp>currentStamp)byEmployee.set(s.employee_id,s)});if(selectedSnapshot)byEmployee.set(selectedSnapshot.employee_id,selectedSnapshot);return Array.from(byEmployee.values())},[filtered,selectedSnapshot])
 useEffect(()=>{if(selectedPlan&&!visiblePlanIds.has(selectedPlan)){setSelectedPlan('');setPlaybackIndex(-1);setPlaying(false);setSelectedEventId('');setIsolateSelected(false)}},[selectedPlan,visiblePlanIds])
 const selectedEvents=useMemo(()=>matchingEvents.filter(e=>e.route_plan_id===selectedPlan&&e.has_gps&&e.latitude!=null&&e.longitude!=null).sort(eventSort),[matchingEvents,selectedPlan])
 useEffect(()=>{if(!playing||selectedEvents.length<2)return;const id=window.setInterval(()=>setPlaybackIndex(i=>{if(i>=selectedEvents.length-1){setPlaying(false);return selectedEvents.length-1}return Math.max(0,i+1)}),Math.max(280,1200/speed));return()=>window.clearInterval(id)},[playing,speed,selectedEvents.length])

 const stats=useMemo(()=>{const active=filtered.filter(s=>ACTIVE_TRACKING_STATUSES.includes(s.tracking_status)).length,visit=filtered.filter(s=>s.tracking_status==='EN_VISITA').length,transit=filtered.filter(s=>s.tracking_status==='EN_TRASLADO').length,stale=date===today?filtered.filter(s=>s.last_event_at&&s.freshness_status==='ANTIGUO'&&!['FINALIZADA','NO_EJECUTADA'].includes(s.tracking_status)).length:0,planned=filtered.reduce((a,s)=>a+Number(s.planned_clients||0),0),visited=filtered.reduce((a,s)=>a+Number(s.visited_clients||0),0);return{active,visit,transit,stale,planned,visited,coverage:pct(visited,planned)}},[filtered,date,today])
 const geoStats=useMemo(()=>{let reliable=0,unreliable=0,distant=0,onSite=0;visibleEvents.forEach(e=>{const geo=geoClassFor(e);if(e.has_gps)reliable++;else if((e.raw_has_gps??(e.latitude!=null&&e.longitude!=null)))unreliable++;if(geo==='DISTANT')distant++;if(geo==='ON_SITE'||geo==='NEAR')onSite++});return{reliable,unreliable,distant,onSite}},[visibleEvents])

 const clear=()=>{setVendor('');setStatus('');setFreshness('');setRegion('');setProvince('');setMunicipality('');setOnlyGps(false);setRouteFilter('');setEventType('');setGpsQuality('');setGeoValidation('');setSelectedPlan('');setSelectedEventId('');setPlaybackIndex(-1);setPlaying(false);setIsolateSelected(false);setViewMode('LIVE')}
 const selectPlan=(id:string)=>{setSelectedPlan(id);setPlaybackIndex(-1);setPlaying(false);setSelectedEventId('')}
 const startPlayback=(planId:string)=>{setSelectedPlan(planId);setViewMode('ROUTES');setSelectedEventId('');const list=matchingEvents.filter(e=>e.route_plan_id===planId&&e.has_gps&&e.latitude!=null&&e.longitude!=null);setPlaybackIndex(list.length?0:-1);setPlaying(list.length>1)}
 const currentEvent=playbackIndex>=0?selectedEvents[playbackIndex]:null
 const selectedEvent=useMemo(()=>visibleEvents.find(e=>e.event_id===selectedEventId)||null,[visibleEvents,selectedEventId])
 const focusedEvent=currentEvent||selectedEvent
 const focusedStop=focusedEvent?.route_stop_id?visibleStops.find(s=>s.route_stop_id===focusedEvent.route_stop_id)||null:null
 const focusedGeo=geoClassFor(focusedEvent)
 const compareEvent=(e:TrackingEvent)=>{setSelectedPlan(e.route_plan_id);setSelectedEventId(e.event_id);setPlaybackIndex(-1);setPlaying(false);setViewMode('QUALITY');setIsolateSelected(false)}

 return <div className="page-stack tracking-page">
  <div className="page-head"><div><span className="eyebrow">LIVE OPERATIONS · FIELD TRACKING</span><h2>Tracking de calle</h2><p>Control operativo, recorridos multi-vendedor y calidad geográfica sobre registros GPS reales. Una anomalía nunca bloquea la gestión.</p></div><div className="button-row"><label className="tracking-auto"><input type="checkbox" checked={autoRefresh} disabled={date!==today} onChange={e=>setAutoRefresh(e.target.checked)}/> Auto 30 s</label><button className="secondary" onClick={()=>void load()}><RefreshCw size={16}/> Actualizar</button></div></div>

  <section className="panel tracking-filters"><div className="tracking-filter-grid"><label><span>Fecha</span><input type="date" value={date} max={today} onChange={e=>{setDate(e.target.value);setSelectedPlan('');setSelectedEventId('');setPlaybackIndex(-1);setPlaying(false)}}/></label><label><span>Vendedor</span><select value={vendor} onChange={e=>setVendor(e.target.value)}><option value="">Todos los vendedores</option>{vendors.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label><span>Estado</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos los estados</option><option value="EN_VISITA">En visita</option><option value="EN_TRASLADO">En traslado</option><option value="EVENTUALIDAD">Eventualidad</option><option value="PENDIENTE_CIERRE">Pendiente cierre</option><option value="PLANIFICADA">Planificada</option><option value="FINALIZADA">Finalizada</option><option value="NO_EJECUTADA">No ejecutada</option></select></label><label><span>Frescura</span><select value={freshness} disabled={date!==today} onChange={e=>setFreshness(e.target.value)}><option value="">Todas</option><option value="RECIENTE">≤ 15 min</option><option value="ATENCION">15–30 min</option><option value="ANTIGUO">&gt; 30 min</option><option value="SIN_REGISTRO">Sin registro</option></select></label><label><span>Región oficial</span><select value={region} onChange={e=>{setRegion(e.target.value);setProvince('');setMunicipality('')}}><option value="">Todas</option>{regions.map(v=><option key={v}>{v}</option>)}</select></label><label><span>Provincia oficial</span><select value={province} onChange={e=>{setProvince(e.target.value);setMunicipality('')}}><option value="">Todas</option>{provinces.map(v=><option key={v}>{v}</option>)}</select></label><label><span>Municipio oficial</span><select value={municipality} onChange={e=>setMunicipality(e.target.value)}><option value="">Todos</option>{municipalities.map(v=><option key={v}>{v}</option>)}</select></label><label className="tracking-check"><span>Mapa</span><div><input type="checkbox" checked={onlyGps} onChange={e=>setOnlyGps(e.target.checked)}/> Última ubicación válida</div></label></div>
   <div className="tracking-context-filters"><label><span>Recorrido</span><select value={routeFilter} onChange={e=>setRouteFilter(e.target.value as RouteFilter)}><option value="">Todos los recorridos</option><option value="ACTIVE">Solo activos</option><option value="FINISHED">Finalizados / no ejecutados</option><option value="WITH_GPS">Con puntos GPS</option><option value="ANOMALY">Con anomalías</option></select></label><label><span>Tipo de registro</span><select value={eventType} onChange={e=>setEventType(e.target.value)}><option value="">Todos los eventos</option><option value="ROUTE_START">Inicio ruta</option><option value="VISIT_START">Llegada cliente</option><option value="VISIT_END">Salida cliente</option><option value="INCIDENT_START">Inicio eventualidad</option><option value="INCIDENT_END">Fin eventualidad</option><option value="ROUTE_END">Cierre ruta</option></select></label><label><span>Calidad GPS</span><select value={gpsQuality} onChange={e=>setGpsQuality(e.target.value)}><option value="">Todas</option><option value="RELIABLE">Cualquier GPS confiable</option><option value="EXCELLENT">Excelente</option><option value="GOOD">Buena</option><option value="APPROXIMATE">Aproximada</option><option value="LOW">Baja</option><option value="UNRELIABLE">No confiable</option></select></label><label><span>Registro vs cliente</span><select value={geoValidation} onChange={e=>setGeoValidation(e.target.value as TrackingGeoClass|'')}><option value="">Todas</option><option value="ON_SITE">En punto ≤100 m</option><option value="NEAR">Cercano 101–300 m</option><option value="OUTSIDE">Fuera 301–1,000 m</option><option value="DISTANT">Distante &gt;1 km</option><option value="UNRELIABLE">GPS no confiable</option><option value="NO_TARGET">Sin punto maestro</option></select></label></div>
   <div className="tracking-filter-foot"><span>{filtered.length} jornada(s) visible(s) · {lastRefresh?`actualizado ${lastRefresh.toLocaleTimeString('es-DO',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}`:'sin actualizar'}</span><button className="secondary compact" onClick={clear}><FilterX size={15}/> Limpiar filtros</button></div>
  </section>

  <section className="metric-section"><div className="metric-grid tracking-metrics"><MetricCard icon={<UsersRound/>} label="Vendedores visibles" value={new Set(filtered.map(s=>s.employee_id)).size} note={`${filtered.length} jornada(s)`}/><MetricCard icon={<Route/>} label="Jornadas activas" value={stats.active} note="visita, traslado o eventualidad" tone="info"/><MetricCard icon={<MapPin/>} label="En visita" value={stats.visit} note="último estado operativo" tone="success"/><MetricCard icon={<LocateFixed/>} label="En traslado" value={stats.transit} note="sesión abierta sin visita" tone="info"/><MetricCard icon={<AlertTriangle/>} label="Sin señal reciente" value={stats.stale} note={date===today?'último registro hace más de 30 min':'solo aplica al día actual'} tone={stats.stale?'warning':'neutral'}/><MetricCard icon={<CheckCircle2/>} label="Cobertura visible" value={`${stats.coverage}%`} note={`${stats.visited}/${stats.planned} visitados`} tone="brand"/></div></section>
  <div className="tracking-quality-strip tracking-quality-groups"><div className="tracking-quality-group"><small>Calidad de señal</small><span><ShieldCheck/> GPS confiable <b>{geoStats.reliable}</b></span><span className={geoStats.unreliable?'warning':''}><AlertTriangle/> GPS no confiable <b>{geoStats.unreliable}</b></span></div><div className="tracking-quality-group"><small>Coherencia geográfica</small><span><Target/> En punto / cercano <b>{geoStats.onSite}</b></span><span className={geoStats.distant?'danger':''}><Navigation/> Registros distantes <b>{geoStats.distant}</b></span></div></div>
  {error&&<div className="panel tracking-error"><b>No fue posible cargar Tracking</b><span>{error}</span></div>}

  <section className="tracking-workspace"><div className="panel tracking-map-panel"><div className="tracking-panel-head tracking-map-head"><div><b>{viewMode==='LIVE'?'Mapa operativo en vivo':viewMode==='ROUTES'?'Recorridos y secuencia de paradas':'Auditoría registro vs cliente'}</b><span>{viewMode==='LIVE'?'Una última posición confiable por vendedor':viewMode==='ROUTES'?'Todos los recorridos visibles conservan un color estable por vendedor':'Selecciona un evento para comparar el registro con el punto maestro'}</span></div><div className="tracking-mode-switch"><button className={viewMode==='LIVE'?'active':''} onClick={()=>setViewMode('LIVE')}><LocateFixed/> En vivo</button><button className={viewMode==='ROUTES'?'active':''} onClick={()=>{setViewMode('ROUTES');setShowStops(true)}}><Layers3/> Recorridos</button><button className={viewMode==='QUALITY'?'active':''} onClick={()=>setViewMode('QUALITY')}><Target/> Calidad GPS</button></div></div><div className="tracking-map-options"><label><input type="checkbox" checked={showStops} onChange={e=>setShowStops(e.target.checked)}/> {viewMode==='QUALITY'?'Ver puntos maestro':'Ver paradas'}</label>{selectedPlan&&viewMode!=='LIVE'&&<label><input type="checkbox" checked={isolateSelected} onChange={e=>setIsolateSelected(e.target.checked)}/> {viewMode==='QUALITY'?'Solo jornada seleccionada':'Solo ruta seleccionada'}</label>}<span>{viewMode==='ROUTES'?'Número = secuencia · color = vendedor · símbolo = estado':viewMode==='QUALITY'?'R = registro · C = cliente · auditoría no bloqueante':'Solo ubicaciones GPS confiables'}</span></div>{loading?<div className="tracking-map-loading">Cargando operación...</div>:<LiveTrackingMap snapshots={mapSnapshots} stops={visibleStops} events={visibleEvents} selectedRoutePlanId={selectedPlan} selectedEventId={selectedEventId} playbackIndex={playbackIndex} showStops={showStops} viewMode={viewMode} isolateSelected={isolateSelected} onPlanSelect={selectPlan} onEventSelect={id=>{setSelectedEventId(id);setPlaybackIndex(-1);setPlaying(false)}}/>}</div>
   <aside className="panel tracking-roster"><div className="tracking-panel-head"><div><b>Fuerza de calle</b><span>Seleccionar destaca una ruta sin ocultar las demás.</span></div><span className="badge">{filtered.length}</span></div><div className="tracking-seller-list">{filtered.map(s=>{const color=routeColorFor(s.employee_id,employeeIds),planEvents=eventsByPlan.get(s.route_plan_id)||[],lastEvent=planEvents.length?planEvents[planEvents.length-1]:null,lastGeo=geoClassFor(lastEvent);return <article key={s.route_plan_id} className={`tracking-seller-card ${selectedPlan===s.route_plan_id?'selected':''}`} style={{'--route-color':color} as CSSProperties}><button className="tracking-seller-main" onClick={()=>selectPlan(s.route_plan_id)}><div className="tracking-route-identity"><i style={{background:color}}/><div className={`tracking-status-orb ${statusClass(s.tracking_status)}`}>{s.full_name.slice(0,1)}</div></div><div><b>{s.full_name}</b><span>{statusLabel(s.tracking_status)} · {date===today?age(s.last_event_age_minutes):time(s.last_event_at)}</span><small>{s.last_subject_name?`${s.last_event_label||'Último registro'} · ${s.last_subject_name}`:s.last_event_label||'Sin evento GPS'}</small><small>Siguiente: {s.next_subject_name||'Sin parada pendiente'} · {s.planned_clients} parada(s)</small></div></button><div className="tracking-seller-stats"><span><b>{s.visited_clients}/{s.planned_clients}</b> visitas</span><span><b>{Number(s.coverage_pct||0)}%</b> cobertura</span><span><b>{duration(s.route_window_seconds)}</b> calle</span><span><b>{duration(s.visit_seconds)}</b> atención</span></div><div className="tracking-seller-quality"><span className={`gps ${gpsQualityClass(lastEvent?.gps_quality||s.last_gps_quality)}`}>GPS {gpsQualityLabel(lastEvent?.gps_quality||s.last_gps_quality)}</span>{lastEvent&&<span className={`geo ${geoClassTone(lastGeo)}`}>{geoClassLabel(lastGeo)}</span>}</div><div className="tracking-seller-actions"><button className="secondary compact" onClick={()=>{selectPlan(s.route_plan_id);setViewMode('ROUTES')}}><Eye size={14}/> Ver ruta</button><button className="secondary compact" disabled={!planEvents.some(e=>e.has_gps)} onClick={()=>startPlayback(s.route_plan_id)}><Play size={14}/> Reproducir</button>{lastEvent&&<button className="secondary compact" onClick={()=>compareEvent(lastEvent)}><Target size={14}/> Calidad</button>}</div></article>})}{!loading&&!filtered.length&&<div className="empty-state"><b>No hay jornadas para estos filtros.</b><span>Pruebe otra fecha o quite segmentaciones.</span></div>}</div></aside>
  </section>

  {focusedEvent&&<section className="panel tracking-geo-detail"><div className="tracking-panel-head"><div><b>Validación geográfica del registro</b><span>{focusedEvent.full_name} · {eventTypeLabel(focusedEvent.event_type)} · {time(focusedEvent.event_at)}</span></div><span className={`tracking-geo-badge ${geoClassTone(focusedGeo)}`}>{geoClassLabel(focusedGeo)}</span></div><div className="tracking-geo-grid"><div><span>Evento</span><b>{focusedEvent.event_label}</b><small>{focusedEvent.subject_name||'Operación de ruta'}{focusedEvent.stop_order?` · parada ${focusedEvent.stop_order}`:''}</small></div><div><span>Calidad GPS</span><b>{gpsQualityLabel(focusedEvent.gps_quality)}</b><small>{formatAccuracy(focusedEvent.accuracy_m)}</small></div><div><span>Distancia al cliente</span><b>{formatDistance(focusedEvent.distance_to_target_m)}</b><small>{focusedStop?focusedStop.subject_name:'Sin punto maestro asociado'}</small></div><div><span>Lugar registrado</span><b>{focusedEvent.latitude!=null&&focusedEvent.longitude!=null?`${Number(focusedEvent.latitude).toFixed(5)}, ${Number(focusedEvent.longitude).toFixed(5)}`:'Sin coordenada'}</b><small>{focusedEvent.has_gps?'Apto para mapa':'No usar como evidencia exacta'}</small></div><div><span>Ubicación cliente</span><b>{focusedStop?.latitude!=null&&focusedStop?.longitude!=null?`${Number(focusedStop.latitude).toFixed(5)}, ${Number(focusedStop.longitude).toFixed(5)}`:'No disponible'}</b><small>{[focusedStop?.official_province,focusedStop?.official_municipality].filter(Boolean).join(' · ')||'—'}</small></div><div><span>Auditoría</span><b>{focusedEvent.location_exception_code||'Sin excepción automática'}</b><small>{focusedEvent.location_exception_text||'La gestión se conserva sin bloqueo.'}</small></div></div><div className="tracking-geo-actions">{focusedEvent.latitude!=null&&focusedEvent.longitude!=null&&focusedStop?.latitude!=null&&focusedStop?.longitude!=null&&<button className="primary compact" onClick={()=>compareEvent(focusedEvent)}><Target size={15}/> Comparar registro vs cliente</button>}<span>La distancia y la precisión son evidencia de auditoría; no determinan por sí solas la calidad comercial del vendedor.</span></div></section>}

  {selectedPlan&&<section className="panel tracking-playback"><div className="tracking-panel-head"><div><b>Reproducción de recorrido{selectedSnapshot?` · ${selectedSnapshot.full_name}`:''}</b><span>Jornada individual · puntos GPS confiables según los filtros actuales.</span></div><button className="secondary compact" onClick={()=>{setSelectedPlan('');setSelectedEventId('');setPlaybackIndex(-1);setPlaying(false);setIsolateSelected(false)}}>Cerrar detalle</button></div><div className="tracking-playback-controls"><button className="icon-btn" disabled={!selectedEvents.length} onClick={()=>{setPlaybackIndex(0);setPlaying(false);setSelectedEventId(selectedEvents[0]?.event_id||'')}} title="Inicio"><SkipBack/></button><button className="primary tracking-play" disabled={selectedEvents.length<2} onClick={()=>{if(playbackIndex<0){setPlaybackIndex(0);setSelectedEventId(selectedEvents[0]?.event_id||'')}setPlaying(v=>!v)}}>{playing?<Pause/>:<Play/>}{playing?'Pausar':'Reproducir'}</button><button className="icon-btn" disabled={!selectedEvents.length} onClick={()=>{setPlaying(false);setPlaybackIndex(i=>{const next=Math.min(selectedEvents.length-1,Math.max(0,i+1));setSelectedEventId(selectedEvents[next]?.event_id||'');return next})}} title="Siguiente"><SkipForward/></button><button className="secondary compact" onClick={()=>{setPlaying(false);setPlaybackIndex(-1);setSelectedEventId('')}}><RotateCcw size={15}/> Ruta completa</button><select value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={1}>1x</option><option value={2}>2x</option><option value={4}>4x</option></select><div className="tracking-progress"><div style={{width:selectedEvents.length&&playbackIndex>=0?`${((playbackIndex+1)/selectedEvents.length)*100}%`:'0%'}}/></div><span>{playbackIndex>=0?`${playbackIndex+1}/${selectedEvents.length}`:`${selectedEvents.length} puntos`}</span></div>{currentEvent&&<div className="tracking-current-event"><Clock3/><div><b>{eventTypeLabel(currentEvent.event_type)}</b><span>{time(currentEvent.event_at)}{currentEvent.subject_name?` · ${currentEvent.subject_name}`:''}</span><small>{formatAccuracy(currentEvent.accuracy_m)} · {geoClassLabel(geoClassFor(currentEvent))}{currentEvent.distance_to_target_m!=null?` · ${formatDistance(currentEvent.distance_to_target_m)} al cliente`:''}</small></div></div>}
   <div className="tracking-timeline-viewport">{selectedEvents.length?<div className="tracking-timeline">{selectedEvents.map((e,i)=>{const geo=geoClassFor(e);return <button key={e.event_id} className={`tracking-timeline-item ${i===playbackIndex?'active':''}`} onClick={()=>{setPlaying(false);setPlaybackIndex(i);setSelectedEventId(e.event_id)}}><span className="tracking-timeline-time">{time(e.event_at)}</span><div className="tracking-timeline-rail"><i/></div><div className="tracking-timeline-body"><div className="tracking-timeline-title"><i className={`tracking-event-kind ${eventKindClass(e.event_type)}`} aria-hidden="true"/><b>{eventTypeLabel(e.event_type)}</b><span className={`tracking-mini-badge ${geoClassTone(geo)}`}>{geoClassLabel(geo)}</span></div><small>{e.subject_name||'Operación de ruta'}{e.stop_order?` · parada ${e.stop_order}`:''}</small><em>{formatAccuracy(e.accuracy_m)}{e.distance_to_target_m!=null?` · ${formatDistance(e.distance_to_target_m)}`:''}</em></div></button>})}</div>:<div className="tracking-timeline-empty"><b>No hay puntos GPS confiables para estos filtros.</b><span>Quita filtros de evento/calidad o selecciona otra jornada.</span></div>}</div>
  </section>}
 </div>
}
