import { useEffect,useMemo,useState } from 'react'
import { AlertTriangle,CheckCircle2,Clock3,Eye,FilterX,LocateFixed,MapPin,Pause,Play,RefreshCw,RotateCcw,Route,SkipBack,SkipForward,UsersRound } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { MetricCard } from '../components/MetricCard'
import { LiveTrackingMap } from '../components/LiveTrackingMap'
import type { TrackingEvent,TrackingSnapshot,TrackingStop } from '../components/LiveTrackingMap'
import '../styles/tracking.css'

const rdDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Santo_Domingo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const duration=(seconds=0)=>{const s=Math.max(0,Math.round(Number(seconds)||0)),h=Math.floor(s/3600),m=Math.floor((s%3600)/60);return h?`${h} h ${m} min`:`${m} min`}
const time=(value?:string|null)=>value?new Date(value).toLocaleTimeString('es-DO',{hour:'2-digit',minute:'2-digit'}):'—'
const age=(minutes?:number|null)=>minutes==null?'Sin registro':minutes<1?'Ahora':minutes<60?`Hace ${minutes} min`:`Hace ${Math.floor(minutes/60)} h ${minutes%60} min`
const pct=(n:number,d:number)=>d?Math.round(n/d*1000)/10:0
const uniq=(values:Array<string|null|undefined>)=>Array.from(new Set(values.filter(Boolean) as string[])).sort((a,b)=>a.localeCompare(b,'es'))
const statusLabel=(s:string)=>({EN_VISITA:'En visita',EN_TRASLADO:'En traslado',EVENTUALIDAD:'Eventualidad',PENDIENTE_CIERRE:'Pendiente cierre',PLANIFICADA:'Planificada',FINALIZADA:'Finalizada',NO_EJECUTADA:'No ejecutada'} as Record<string,string>)[s]||s.replaceAll('_',' ')
const statusClass=(s:string)=>s.toLowerCase().replaceAll('_','-')

export function Tracking(){
 const today=rdDate();const[date,setDate]=useState(today),[snapshots,setSnapshots]=useState<TrackingSnapshot[]>([]),[stops,setStops]=useState<TrackingStop[]>([]),[events,setEvents]=useState<TrackingEvent[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const[vendor,setVendor]=useState(''),[status,setStatus]=useState(''),[freshness,setFreshness]=useState(''),[region,setRegion]=useState(''),[province,setProvince]=useState(''),[municipality,setMunicipality]=useState(''),[onlyGps,setOnlyGps]=useState(false),[showStops,setShowStops]=useState(true),[autoRefresh,setAutoRefresh]=useState(true)
 const[selectedPlan,setSelectedPlan]=useState(''),[playbackIndex,setPlaybackIndex]=useState(-1),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1),[lastRefresh,setLastRefresh]=useState<Date|null>(null)
 const load=async()=>{setLoading(true);setError('');const[a,b,c]=await Promise.all([supabase.from('executive_tracking_snapshot_v1').select('*').eq('route_date',date).order('full_name'),supabase.from('executive_tracking_stops_v1').select('*').eq('route_date',date).order('employee_id').order('stop_order'),supabase.from('executive_tracking_events_v1').select('*').eq('route_date',date).order('event_at',{ascending:true})]);const err=a.error||b.error||c.error;if(err)setError(err.message);setSnapshots((a.data||[]) as TrackingSnapshot[]);setStops((b.data||[]) as TrackingStop[]);setEvents((c.data||[]) as TrackingEvent[]);setLastRefresh(new Date());setLoading(false)}
 useEffect(()=>{void load()},[date])
 useEffect(()=>{if(!autoRefresh||date!==today)return;const id=window.setInterval(()=>void load(),30000);return()=>window.clearInterval(id)},[autoRefresh,date,today])
 const vendors=useMemo(()=>{const byId=new Map<string,string>();snapshots.forEach(s=>byId.set(s.employee_id,s.full_name));return Array.from(byId.entries()).sort((a,b)=>a[1].localeCompare(b[1],'es'))},[snapshots])
 const regions=useMemo(()=>uniq(snapshots.flatMap(s=>s.official_regions||[])),[snapshots]),provinces=useMemo(()=>uniq(snapshots.filter(s=>!region||(s.official_regions||[]).includes(region)).flatMap(s=>s.official_provinces||[])),[snapshots,region]),municipalities=useMemo(()=>uniq(snapshots.filter(s=>(!region||(s.official_regions||[]).includes(region))&&(!province||(s.official_provinces||[]).includes(province))).flatMap(s=>s.official_municipalities||[])),[snapshots,region,province])
 const filtered=useMemo(()=>snapshots.filter(s=>{if(vendor&&s.employee_id!==vendor)return false;if(status&&s.tracking_status!==status)return false;if(date===today&&freshness&&s.freshness_status!==freshness)return false;if(region&&!(s.official_regions||[]).includes(region))return false;if(province&&!(s.official_provinces||[]).includes(province))return false;if(municipality&&!(s.official_municipalities||[]).includes(municipality))return false;if(onlyGps&&(s.last_latitude==null||s.last_longitude==null))return false;return true}),[snapshots,vendor,status,freshness,region,province,municipality,onlyGps,date,today])
 const visiblePlanIds=useMemo(()=>new Set(filtered.map(s=>s.route_plan_id)),[filtered]),visibleStops=useMemo(()=>stops.filter(s=>visiblePlanIds.has(s.route_plan_id)),[stops,visiblePlanIds]),visibleEvents=useMemo(()=>events.filter(e=>visiblePlanIds.has(e.route_plan_id)),[events,visiblePlanIds])
 const selectedSnapshot=useMemo(()=>filtered.find(s=>s.route_plan_id===selectedPlan)||null,[filtered,selectedPlan])
 const mapSnapshots=useMemo(()=>{const byEmployee=new Map<string,TrackingSnapshot>();filtered.forEach(s=>{const current=byEmployee.get(s.employee_id),stamp=s.last_event_at?new Date(s.last_event_at).getTime():-1,currentStamp=current?.last_event_at?new Date(current.last_event_at).getTime():-1;if(!current||stamp>currentStamp)byEmployee.set(s.employee_id,s)});if(selectedSnapshot)byEmployee.set(selectedSnapshot.employee_id,selectedSnapshot);return Array.from(byEmployee.values())},[filtered,selectedSnapshot])
 useEffect(()=>{if(selectedPlan&&!visiblePlanIds.has(selectedPlan)){setSelectedPlan('');setPlaybackIndex(-1);setPlaying(false)}},[selectedPlan,visiblePlanIds])
 const selectedEvents=useMemo(()=>visibleEvents.filter(e=>e.route_plan_id===selectedPlan&&e.has_gps&&e.latitude!=null&&e.longitude!=null).sort((a,b)=>new Date(a.event_at).getTime()-new Date(b.event_at).getTime()),[visibleEvents,selectedPlan])
 useEffect(()=>{if(!playing||selectedEvents.length<2)return;const id=window.setInterval(()=>setPlaybackIndex(i=>{if(i>=selectedEvents.length-1){setPlaying(false);return selectedEvents.length-1}return Math.max(0,i+1)}),Math.max(280,1200/speed));return()=>window.clearInterval(id)},[playing,speed,selectedEvents.length])
 const stats=useMemo(()=>{const active=filtered.filter(s=>['EN_VISITA','EN_TRASLADO','EVENTUALIDAD','PENDIENTE_CIERRE'].includes(s.tracking_status)).length,visit=filtered.filter(s=>s.tracking_status==='EN_VISITA').length,transit=filtered.filter(s=>s.tracking_status==='EN_TRASLADO').length,stale=date===today?filtered.filter(s=>s.last_event_at&&s.freshness_status==='ANTIGUO'&&!['FINALIZADA','NO_EJECUTADA'].includes(s.tracking_status)).length:0,planned=filtered.reduce((a,s)=>a+Number(s.planned_clients||0),0),visited=filtered.reduce((a,s)=>a+Number(s.visited_clients||0),0);return{active,visit,transit,stale,planned,visited,coverage:pct(visited,planned)}},[filtered,date,today])
 const clear=()=>{setVendor('');setStatus('');setFreshness('');setRegion('');setProvince('');setMunicipality('');setOnlyGps(false);setSelectedPlan('');setPlaybackIndex(-1);setPlaying(false)}
 const selectPlan=(id:string)=>{setSelectedPlan(id);setPlaybackIndex(-1);setPlaying(false)}
 const startPlayback=(planId:string)=>{setSelectedPlan(planId);const list=visibleEvents.filter(e=>e.route_plan_id===planId&&e.has_gps);setPlaybackIndex(list.length?0:-1);setPlaying(list.length>1)}
 const currentEvent=playbackIndex>=0?selectedEvents[playbackIndex]:null
 return <div className="page-stack tracking-page">
  <div className="page-head"><div><span className="eyebrow">LIVE OPERATIONS · FIELD TRACKING</span><h2>Tracking de calle</h2><p>Último registro GPS real, estado operativo inferido, paradas y reproducción temporal. No confunde un registro antiguo con ubicación actual.</p></div><div className="button-row"><label className="tracking-auto"><input type="checkbox" checked={autoRefresh} disabled={date!==today} onChange={e=>setAutoRefresh(e.target.checked)}/> Auto 30 s</label><button className="secondary" onClick={()=>void load()}><RefreshCw size={16}/> Actualizar</button></div></div>
  <section className="panel tracking-filters"><div className="tracking-filter-grid"><label><span>Fecha</span><input type="date" value={date} max={today} onChange={e=>{setDate(e.target.value);setSelectedPlan('');setPlaybackIndex(-1);setPlaying(false)}}/></label><label><span>Vendedor</span><select value={vendor} onChange={e=>setVendor(e.target.value)}><option value="">Todos los vendedores</option>{vendors.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label><span>Estado</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos los estados</option><option value="EN_VISITA">En visita</option><option value="EN_TRASLADO">En traslado</option><option value="EVENTUALIDAD">Eventualidad</option><option value="PENDIENTE_CIERRE">Pendiente cierre</option><option value="PLANIFICADA">Planificada</option><option value="FINALIZADA">Finalizada</option><option value="NO_EJECUTADA">No ejecutada</option></select></label><label><span>Frescura</span><select value={freshness} disabled={date!==today} onChange={e=>setFreshness(e.target.value)}><option value="">Todas</option><option value="RECIENTE">≤ 15 min</option><option value="ATENCION">15–30 min</option><option value="ANTIGUO">&gt; 30 min</option><option value="SIN_REGISTRO">Sin registro</option></select></label><label><span>Región oficial</span><select value={region} onChange={e=>{setRegion(e.target.value);setProvince('');setMunicipality('')}}><option value="">Todas</option>{regions.map(v=><option key={v}>{v}</option>)}</select></label><label><span>Provincia oficial</span><select value={province} onChange={e=>{setProvince(e.target.value);setMunicipality('')}}><option value="">Todas</option>{provinces.map(v=><option key={v}>{v}</option>)}</select></label><label><span>Municipio oficial</span><select value={municipality} onChange={e=>setMunicipality(e.target.value)}><option value="">Todos</option>{municipalities.map(v=><option key={v}>{v}</option>)}</select></label><label className="tracking-check"><span>Mapa</span><div><input type="checkbox" checked={onlyGps} onChange={e=>setOnlyGps(e.target.checked)}/> Solo con GPS</div></label></div><div className="tracking-filter-foot"><span>{filtered.length} jornada(s) visible(s) · {lastRefresh?`actualizado ${lastRefresh.toLocaleTimeString('es-DO',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}`:'sin actualizar'}</span><button className="secondary compact" onClick={clear}><FilterX size={15}/> Limpiar filtros</button></div></section>
  <section className="metric-section"><div className="metric-grid tracking-metrics"><MetricCard icon={<UsersRound/>} label="Vendedores visibles" value={new Set(filtered.map(s=>s.employee_id)).size} note={`${filtered.length} jornada(s)`}/><MetricCard icon={<Route/>} label="Jornadas activas" value={stats.active} note="visita, traslado o eventualidad" tone="info"/><MetricCard icon={<MapPin/>} label="En visita" value={stats.visit} note="último estado operativo" tone="success"/><MetricCard icon={<LocateFixed/>} label="En traslado" value={stats.transit} note="sesión abierta sin visita" tone="info"/><MetricCard icon={<AlertTriangle/>} label="Sin actualización" value={stats.stale} note={date===today?'más de 30 min':'solo aplica al día actual'} tone={stats.stale?'warning':'neutral'}/><MetricCard icon={<CheckCircle2/>} label="Cobertura visible" value={`${stats.coverage}%`} note={`${stats.visited}/${stats.planned} visitados`} tone="brand"/></div></section>
  {error&&<div className="panel tracking-error"><b>No fue posible cargar Tracking</b><span>{error}</span></div>}
  <section className="tracking-workspace"><div className="panel tracking-map-panel"><div className="tracking-panel-head"><div><b>Mapa operativo</b><span>{selectedPlan?'Jornada seleccionada · recorrido y paradas':'Vista conjunta · una última posición registrada por vendedor'}</span></div><label><input type="checkbox" checked={showStops} onChange={e=>setShowStops(e.target.checked)}/> Ver paradas</label></div>{loading?<div className="tracking-map-loading">Cargando operación...</div>:<LiveTrackingMap snapshots={mapSnapshots} stops={visibleStops} events={visibleEvents} selectedRoutePlanId={selectedPlan} playbackIndex={playbackIndex} showStops={showStops}/>}</div>
   <aside className="panel tracking-roster"><div className="tracking-panel-head"><div><b>Fuerza de calle</b><span>Una tarjeta por jornada. El recorrido nunca mezcla planes distintos.</span></div><span className="badge">{filtered.length}</span></div><div className="tracking-seller-list">{filtered.map(s=><article key={s.route_plan_id} className={`tracking-seller-card ${selectedPlan===s.route_plan_id?'selected':''}`}><button className="tracking-seller-main" onClick={()=>selectPlan(s.route_plan_id)}><div className={`tracking-status-orb ${statusClass(s.tracking_status)}`}>{s.full_name.slice(0,1)}</div><div><b>{s.full_name}</b><span>{statusLabel(s.tracking_status)} · {date===today?age(s.last_event_age_minutes):time(s.last_event_at)}</span><small>{s.last_subject_name?`${s.last_event_label||'Último registro'} · ${s.last_subject_name}`:s.last_event_label||'Sin evento GPS'}</small><small>Siguiente: {s.next_subject_name||'Sin parada pendiente'} · {s.planned_clients} parada(s)</small></div></button><div className="tracking-seller-stats"><span><b>{s.visited_clients}/{s.planned_clients}</b> visitas</span><span><b>{Number(s.coverage_pct||0)}%</b> cobertura</span><span><b>{duration(s.route_window_seconds)}</b> calle</span><span><b>{duration(s.visit_seconds)}</b> atención</span></div><div className="tracking-seller-actions"><button className="secondary compact" onClick={()=>selectPlan(s.route_plan_id)}><Eye size={14}/> Ubicar</button><button className="secondary compact" disabled={!visibleEvents.some(e=>e.route_plan_id===s.route_plan_id&&e.has_gps)} onClick={()=>startPlayback(s.route_plan_id)}><Play size={14}/> Recorrido</button></div></article>)}{!loading&&!filtered.length&&<div className="empty-state"><b>No hay jornadas para estos filtros.</b><span>Pruebe otra fecha o quite segmentaciones.</span></div>}</div></aside>
  </section>
  {selectedPlan&&<section className="panel tracking-playback"><div className="tracking-panel-head"><div><b>Reproducción de recorrido{selectedSnapshot?` · ${selectedSnapshot.full_name}`:''}</b><span>Jornada individual · puntos GPS registrados; los tramos entre ellos son estimados.</span></div><button className="secondary compact" onClick={()=>{setSelectedPlan('');setPlaybackIndex(-1);setPlaying(false)}}>Cerrar detalle</button></div><div className="tracking-playback-controls"><button className="icon-btn" disabled={!selectedEvents.length} onClick={()=>{setPlaybackIndex(0);setPlaying(false)}} title="Inicio"><SkipBack/></button><button className="primary tracking-play" disabled={selectedEvents.length<2} onClick={()=>{if(playbackIndex<0)setPlaybackIndex(0);setPlaying(v=>!v)}}>{playing?<Pause/>:<Play/>}{playing?'Pausar':'Reproducir'}</button><button className="icon-btn" disabled={!selectedEvents.length} onClick={()=>{setPlaying(false);setPlaybackIndex(i=>Math.min(selectedEvents.length-1,Math.max(0,i+1)))}} title="Siguiente"><SkipForward/></button><button className="secondary compact" onClick={()=>{setPlaying(false);setPlaybackIndex(-1)}}><RotateCcw size={15}/> Ruta completa</button><select value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={1}>1x</option><option value={2}>2x</option><option value={4}>4x</option></select><div className="tracking-progress"><div style={{width:selectedEvents.length&&playbackIndex>=0?`${((playbackIndex+1)/selectedEvents.length)*100}%`:'0%'}}/></div><span>{playbackIndex>=0?`${playbackIndex+1}/${selectedEvents.length}`:`${selectedEvents.length} puntos`}</span></div>{currentEvent&&<div className="tracking-current-event"><Clock3/><div><b>{currentEvent.event_label}</b><span>{time(currentEvent.event_at)}{currentEvent.subject_name?` · ${currentEvent.subject_name}`:''}</span><small>Precisión GPS: {currentEvent.accuracy_m?`${Math.round(Number(currentEvent.accuracy_m))} m`:'no disponible'}</small></div></div>}
   <div className="tracking-timeline">{selectedEvents.map((e,i)=><button key={e.event_id} className={i===playbackIndex?'active':''} onClick={()=>{setPlaying(false);setPlaybackIndex(i)}}><span>{time(e.event_at)}</span><i/><div><b>{e.event_label}</b><small>{e.subject_name||'Operación de ruta'}{e.stop_order?` · parada ${e.stop_order}`:''}</small></div></button>)}</div>
  </section>}
 </div>
}
