import { useEffect,useMemo,useRef } from 'react'
import L from 'leaflet'
import 'leaflet/dist/leaflet.css'
import '../styles/tracking.css'

export type TrackingSnapshot={
  route_plan_id:string;route_session_id?:string|null;employee_id:string;full_name:string;job_title?:string|null;route_date:string;tracking_status:string;journey_status?:string|null;
  planned_clients:number;visited_clients:number;coverage_pct:number;route_window_seconds:number;visit_seconds:number;estimated_distance_m:number;
  last_event_id?:string|null;last_event_type?:string|null;last_event_at?:string|null;last_latitude?:number|null;last_longitude?:number|null;last_accuracy_m?:number|null;last_subject_name?:string|null;last_event_label?:string|null;last_event_age_minutes?:number|null;freshness_status:string;
  next_route_stop_id?:string|null;next_stop_order?:number|null;next_subject_name?:string|null;next_latitude?:number|null;next_longitude?:number|null;
  official_regions?:string[]|null;official_provinces?:string[]|null;official_municipalities?:string[]|null;
}
export type TrackingStop={route_stop_id:string;route_plan_id:string;route_date:string;employee_id:string;full_name:string;stop_order:number;stop_status:string;subject_name:string;latitude?:number|null;longitude?:number|null;official_region?:string|null;official_province?:string|null;official_municipality?:string|null}
export type TrackingEvent={event_id:string;route_plan_id:string;route_session_id?:string|null;employee_id:string;full_name:string;route_date:string;event_type:string;event_at:string;latitude?:number|null;longitude?:number|null;accuracy_m?:number|null;subject_name?:string|null;stop_order?:number|null;event_label:string;has_gps:boolean}

type Props={snapshots:TrackingSnapshot[];stops:TrackingStop[];events:TrackingEvent[];selectedEmployeeId?:string;playbackIndex:number;showStops:boolean}
const CENTER:[number,number]=[18.7357,-70.1627]
const BOUNDS=L.latLngBounds([16.85,-72.85],[20.55,-67.45])
const statusColor=(status:string)=>status==='EN_VISITA'?'#159a66':status==='EN_TRASLADO'?'#2563eb':status==='EVENTUALIDAD'?'#d97706':status==='PENDIENTE_CIERRE'?'#c71f2d':status==='FINALIZADA'?'#64748b':status==='NO_EJECUTADA'?'#a9464d':'#8b9aad'
const stopColor=(status:string)=>status==='VISITADO'?'#159a66':status==='NO_VISITADO'?'#c71f2d':'#8b9aad'
const esc=(value:unknown)=>String(value??'').replace(/[&<>'"]/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]||c))

export function LiveTrackingMap({snapshots,stops,events,selectedEmployeeId='',playbackIndex=-1,showStops}:Props){
 const host=useRef<HTMLDivElement|null>(null),mapRef=useRef<L.Map|null>(null),positionsRef=useRef<L.LayerGroup|null>(null),stopsRef=useRef<L.LayerGroup|null>(null),trackRef=useRef<L.LayerGroup|null>(null)
 const selectedEvents=useMemo(()=>events.filter(e=>e.employee_id===selectedEmployeeId&&e.has_gps&&e.latitude!=null&&e.longitude!=null).sort((a,b)=>new Date(a.event_at).getTime()-new Date(b.event_at).getTime()),[events,selectedEmployeeId])
 useEffect(()=>{if(!host.current||mapRef.current)return;const map=L.map(host.current,{zoomControl:false,preferCanvas:true,minZoom:7,maxBounds:BOUNDS,maxBoundsViscosity:.65}).setView(CENTER,8.5);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,maxNativeZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);positionsRef.current=L.layerGroup().addTo(map);stopsRef.current=L.layerGroup().addTo(map);trackRef.current=L.layerGroup().addTo(map);mapRef.current=map;requestAnimationFrame(()=>map.invalidateSize());return()=>{map.remove();mapRef.current=null}},[])
 useEffect(()=>{const map=mapRef.current,layer=positionsRef.current;if(!map||!layer)return;layer.clearLayers();const points:L.LatLngExpression[]=[];snapshots.forEach(s=>{if(s.last_latitude==null||s.last_longitude==null)return;const selected=s.employee_id===selectedEmployeeId,color=statusColor(s.tracking_status);points.push([s.last_latitude,s.last_longitude]);const marker=L.circleMarker([s.last_latitude,s.last_longitude],{radius:selected?11:8,weight:selected?4:3,color:'#fff',fillColor:color,fillOpacity:.97});const age=s.last_event_age_minutes==null?'sin hora':s.last_event_age_minutes<1?'ahora':`hace ${s.last_event_age_minutes} min`;marker.bindTooltip(`<div class="tracking-map-tooltip"><b>${esc(s.full_name)}</b><span>${esc(s.tracking_status.replaceAll('_',' '))}</span><span>${esc(s.last_event_label||'Último registro')} · ${esc(age)}</span>${s.last_subject_name?`<strong>${esc(s.last_subject_name)}</strong>`:''}<small>Coordenada del último evento registrado</small></div>`,{direction:'top',opacity:.98});marker.addTo(layer);L.marker([s.last_latitude,s.last_longitude],{interactive:false,icon:L.divIcon({className:'tracking-initial-marker',html:`<span>${esc(s.full_name.slice(0,1).toUpperCase())}</span>`,iconSize:[22,22],iconAnchor:[11,11]})}).addTo(layer)});if(!selectedEmployeeId&&points.length>1){const bounds=L.latLngBounds(points);if(bounds.isValid())map.fitBounds(bounds.pad(.18),{maxZoom:13})}},[snapshots,selectedEmployeeId])
 useEffect(()=>{const layer=stopsRef.current;if(!layer)return;layer.clearLayers();if(!showStops)return;stops.filter(s=>!selectedEmployeeId||s.employee_id===selectedEmployeeId).forEach(s=>{if(s.latitude==null||s.longitude==null)return;const marker=L.circleMarker([s.latitude,s.longitude],{radius:selectedEmployeeId?6:4,weight:2,color:'#fff',fillColor:stopColor(s.stop_status),fillOpacity:.88});marker.bindTooltip(`<div class="tracking-map-tooltip"><b>${s.stop_order}. ${esc(s.subject_name)}</b><span>${esc(s.stop_status.replaceAll('_',' '))}</span><span>${esc(s.full_name)}</span></div>`,{direction:'top',opacity:.96});marker.addTo(layer)})},[stops,selectedEmployeeId,showStops])
 useEffect(()=>{const map=mapRef.current,layer=trackRef.current;if(!map||!layer)return;layer.clearLayers();if(!selectedEmployeeId||selectedEvents.length===0)return;const limit=playbackIndex>=0?Math.min(playbackIndex+1,selectedEvents.length):selectedEvents.length;const visible=selectedEvents.slice(0,limit),points=visible.map(e=>[e.latitude!,e.longitude!] as [number,number]);if(points.length>1)L.polyline(points,{color:'#2563eb',weight:4,opacity:.72,dashArray:'8 7'}).addTo(layer);selectedEvents.forEach((e,index)=>{const reached=playbackIndex<0||index<=playbackIndex;const marker=L.circleMarker([e.latitude!,e.longitude!],{radius:index===playbackIndex?8:4,weight:2,color:'#fff',fillColor:reached?'#2563eb':'#cbd5e1',fillOpacity:reached?.95:.5});marker.bindTooltip(`<div class="tracking-map-tooltip"><b>${esc(e.event_label)}</b><span>${new Date(e.event_at).toLocaleTimeString('es-DO',{hour:'2-digit',minute:'2-digit'})}</span>${e.subject_name?`<strong>${esc(e.subject_name)}</strong>`:''}<small>Punto GPS registrado</small></div>`,{direction:'top'});marker.addTo(layer)});if(playbackIndex>=0&&visible.length){const current=visible[visible.length-1];L.circleMarker([current.latitude!,current.longitude!],{radius:13,weight:3,color:'#2563eb',fillColor:'#fff',fillOpacity:.85}).addTo(layer);map.flyTo([current.latitude!,current.longitude!],Math.max(map.getZoom(),14),{duration:.45})}else{const bounds=L.latLngBounds(points);if(bounds.isValid())map.fitBounds(bounds.pad(.2),{maxZoom:15})}},[selectedEmployeeId,selectedEvents,playbackIndex])
 return <div className="tracking-map-shell"><div ref={host} className="tracking-map-host"/><div className="tracking-map-legend"><span><i className="dot visit"/>En visita</span><span><i className="dot transit"/>En traslado</span><span><i className="dot stale"/>Pendiente/alerta</span><small>Líneas = unión estimada entre puntos GPS registrados</small></div></div>
}
