import { BrowserRouter,Navigate,Route,Routes } from 'react-router-dom'
import { useAuth } from './context/AuthContext'
import { ThemeProvider } from './context/ThemeContext'
import { AppShell } from './components/AppShell'
import { Login } from './pages/Login'
import { Dashboard } from './pages/Dashboard'
import { Clients } from './pages/Clients'
import { MapPage } from './pages/MapPage'
import { Planning } from './pages/Planning'
import { Routes as RoutesPage } from './pages/Routes'
import { Capture } from './pages/Capture'
import { Visits } from './pages/Visits'
import { Calls } from './pages/Calls'
import { Agenda } from './pages/Agenda'
import { Reports } from './pages/Reports'
import { Admin } from './pages/Admin'
import { Settings } from './pages/Settings'
import { DataQuality } from './pages/DataQuality'
function Protected(){const {session,loading}=useAuth();if(loading)return <div className="boot-screen"><img src="/logo-karaka.png"/><div className="boot-loader"><i/></div><span>Iniciando sistema...</span></div>;if(!session)return <Login/>;return <ThemeProvider><Routes><Route element={<AppShell/>}><Route index element={<Dashboard/>}/><Route path="clientes" element={<Clients/>}/><Route path="mapa" element={<MapPage/>}/><Route path="planificacion" element={<Planning/>}/><Route path="rutas" element={<RoutesPage/>}/><Route path="captacion" element={<Capture/>}/><Route path="visitas" element={<Visits/>}/><Route path="llamadas" element={<Calls/>}/><Route path="agenda" element={<Agenda/>}/><Route path="reportes" element={<Reports/>}/><Route path="calidad-datos" element={<DataQuality/>}/><Route path="administracion" element={<Admin/>}/><Route path="configuracion" element={<Settings/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Route></Routes></ThemeProvider>}
export default function App(){return <BrowserRouter><Protected/></BrowserRouter>}
